"""
Comprehensive medical laboratory test catalog data.
Used by main.py startup seed and can be re-imported anytime.
"""

DEPARTMENTS = [
    {'code':'HEM',    'name':'Hematology',                'abbr':'HEM',  'color':'#DC143C','order':1},
    {'code':'BIOCHEM','name':'Biochemistry',               'abbr':'BCH',  'color':'#FF8C00','order':2},
    {'code':'HORMONE','name':'Hormones & Endocrinology',   'abbr':'HOR',  'color':'#4169E1','order':3},
    {'code':'MARKER', 'name':'Tumour Markers & Immunology','abbr':'MRK',  'color':'#8B008B','order':4},
    {'code':'SERO',   'name':'Serology & Virology',        'abbr':'SER',  'color':'#2E8B57','order':5},
    {'code':'MICRO',  'name':'Microbiology',               'abbr':'MIC',  'color':'#228B22','order':6},
    {'code':'URINE',  'name':'Urinalysis',                 'abbr':'URN',  'color':'#DAA520','order':7},
    {'code':'COAG',   'name':'Coagulation',                'abbr':'COA',  'color':'#B22222','order':8},
]

# (code, name, short, dept_code, unit, specimen, tube, tat_h, price_rwf, ref_text, order)
TESTS = [
    # HEMATOLOGY
    ('HGB','Hemoglobin','Hb','HEM','g/dL','EDTA Blood','purple_edta',1,1500,'M:13.0-17.5|F:12.0-15.5',1),
    ('RBC','Red Blood Cell Count','RBC','HEM','x10^12/L','EDTA Blood','purple_edta',1,1500,'M:4.5-5.9|F:4.0-5.2',2),
    ('WBC','White Blood Cell Count','WBC','HEM','x10^3/uL','EDTA Blood','purple_edta',1,1500,'4.0-11.0',3),
    ('PLT','Platelet Count','PLT','HEM','x10^3/uL','EDTA Blood','purple_edta',1,1500,'150-450',4),
    ('HCT','Hematocrit','HCT','HEM','%','EDTA Blood','purple_edta',1,500,'M:40-52|F:36-48',5),
    ('MCV','Mean Corpuscular Volume','MCV','HEM','fL','EDTA Blood','purple_edta',1,500,'80-100',6),
    ('MCH','Mean Corpuscular Hemoglobin','MCH','HEM','pg','EDTA Blood','purple_edta',1,500,'27-33',7),
    ('MCHC','MCHC','MCHC','HEM','g/dL','EDTA Blood','purple_edta',1,500,'31-37',8),
    ('RDW','Red Cell Distribution Width','RDW','HEM','%','EDTA Blood','purple_edta',1,500,'11.5-14.5',9),
    ('NEUT_P','Neutrophils %','NEUT%','HEM','%','EDTA Blood','purple_edta',1,500,'40-75',10),
    ('LYMPH_P','Lymphocytes %','LYMPH%','HEM','%','EDTA Blood','purple_edta',1,500,'20-45',11),
    ('MONO_P','Monocytes %','MONO%','HEM','%','EDTA Blood','purple_edta',1,500,'2-10',12),
    ('EOS_P','Eosinophils %','EOS%','HEM','%','EDTA Blood','purple_edta',1,500,'1-6',13),
    ('BASO_P','Basophils %','BASO%','HEM','%','EDTA Blood','purple_edta',1,500,'0-1',14),
    ('NEUT_A','Neutrophils Absolute','NEUT abs','HEM','x10^3/uL','EDTA Blood','purple_edta',1,500,'1.8-7.5',15),
    ('LYMPH_A','Lymphocytes Absolute','LYMPH abs','HEM','x10^3/uL','EDTA Blood','purple_edta',1,500,'1.0-4.5',16),
    ('ESR','Erythrocyte Sedimentation Rate','ESR','HEM','mm/h','EDTA Blood','purple_edta',1,1000,'M:<15|F:<20',17),
    ('RETIC','Reticulocyte Count','Retic','HEM','%','EDTA Blood','purple_edta',2,2000,'0.5-2.5',18),
    ('PBS','Peripheral Blood Smear','PBS','HEM','report','EDTA Blood','purple_edta',4,3000,'No abnormal cells',19),
    ('MAL_RDT','Malaria RDT','Mal RDT','HEM','Pos/Neg','EDTA Blood','purple_edta',1,2000,'Negative',20),
    ('MAL_SM','Malaria Blood Smear','Mal smear','HEM','report','EDTA Blood','purple_edta',2,3000,'Negative',21),
    ('SICKLING','Sickle Cell Screen','Sickling','HEM','Pos/Neg','EDTA Blood','purple_edta',2,2500,'Negative',22),
    ('BLD_GRP','Blood Group ABO/Rh','Blood Grp','HEM','group','EDTA Blood','purple_edta',2,2000,'Report group',23),
    # COAGULATION
    ('PT','Prothrombin Time','PT','COAG','seconds','Citrate Blood','blue_citrate',2,2000,'11-14',1),
    ('INR','INR','INR','COAG','ratio','Citrate Blood','blue_citrate',2,2000,'0.8-1.2',2),
    ('APTT','aPTT','aPTT','COAG','seconds','Citrate Blood','blue_citrate',2,2000,'25-35',3),
    ('FIBRIN','Fibrinogen','Fibrinogen','COAG','g/L','Citrate Blood','blue_citrate',3,3500,'2.0-4.0',4),
    ('DDIMER','D-Dimer','D-Dimer','COAG','mg/L FEU','Citrate Blood','blue_citrate',2,5000,'<0.50',5),
    ('TT','Thrombin Time','TT','COAG','seconds','Citrate Blood','blue_citrate',3,3000,'14-21',6),
    # BIOCHEMISTRY
    ('FBG','Fasting Blood Glucose','FBG','BIOCHEM','mmol/L','Fluoride Blood','grey_fluoride',1,1500,'3.9-6.1',1),
    ('RBG','Random Blood Glucose','RBG','BIOCHEM','mmol/L','Fluoride Blood','grey_fluoride',1,1500,'<11.1',2),
    ('HBA1C','HbA1c','HbA1c','BIOCHEM','%','EDTA Blood','purple_edta',4,5000,'<5.7',3),
    ('UREA','Urea','Urea','BIOCHEM','mmol/L','Serum','yellow_sst',2,1500,'2.5-7.5',4),
    ('CREAT','Creatinine','Creatinine','BIOCHEM','umol/L','Serum','yellow_sst',2,1500,'M:62-115|F:53-97',5),
    ('URIC','Uric Acid','Uric acid','BIOCHEM','umol/L','Serum','yellow_sst',2,2000,'M:200-420|F:143-340',6),
    ('NA','Sodium','Na+','BIOCHEM','mmol/L','Serum','yellow_sst',2,1500,'136-145',7),
    ('K','Potassium','K+','BIOCHEM','mmol/L','Serum','yellow_sst',2,1500,'3.5-5.1',8),
    ('CL','Chloride','Cl-','BIOCHEM','mmol/L','Serum','yellow_sst',2,1500,'98-107',9),
    ('HCO3','Bicarbonate','HCO3-','BIOCHEM','mmol/L','Serum','yellow_sst',2,1500,'22-29',10),
    ('CA','Calcium Total','Ca2+','BIOCHEM','mmol/L','Serum','yellow_sst',2,2000,'2.12-2.62',11),
    ('MG','Magnesium','Mg2+','BIOCHEM','mmol/L','Serum','yellow_sst',2,2000,'0.70-1.05',12),
    ('PHOS','Phosphate','PO4','BIOCHEM','mmol/L','Serum','yellow_sst',2,2000,'0.81-1.45',13),
    ('TPROT','Total Protein','TP','BIOCHEM','g/L','Serum','yellow_sst',2,1500,'60-80',14),
    ('ALB','Albumin','Albumin','BIOCHEM','g/L','Serum','yellow_sst',2,1500,'35-52',15),
    ('ALT','ALT SGPT','ALT','BIOCHEM','U/L','Serum','yellow_sst',2,2000,'M:<45|F:<35',16),
    ('AST','AST SGOT','AST','BIOCHEM','U/L','Serum','yellow_sst',2,2000,'M:<40|F:<32',17),
    ('ALP','Alkaline Phosphatase','ALP','BIOCHEM','U/L','Serum','yellow_sst',2,2000,'40-130',18),
    ('GGT','Gamma-GT','GGT','BIOCHEM','U/L','Serum','yellow_sst',2,2000,'M:<65|F:<45',19),
    ('TBIL','Total Bilirubin','TBil','BIOCHEM','umol/L','Serum','yellow_sst',2,1500,'3-21',20),
    ('DBIL','Direct Bilirubin','DBil','BIOCHEM','umol/L','Serum','yellow_sst',2,1500,'0-5',21),
    ('TCHOL','Total Cholesterol','Chol','BIOCHEM','mmol/L','Serum','yellow_sst',2,2000,'<5.2',22),
    ('LDL','LDL Cholesterol','LDL','BIOCHEM','mmol/L','Serum','yellow_sst',2,2500,'<3.4',23),
    ('HDL','HDL Cholesterol','HDL','BIOCHEM','mmol/L','Serum','yellow_sst',2,2500,'M:>1.0|F:>1.3',24),
    ('TG','Triglycerides','TG','BIOCHEM','mmol/L','Serum','yellow_sst',2,2000,'<1.7',25),
    ('CK','Creatine Kinase','CK','BIOCHEM','U/L','Serum','yellow_sst',4,3000,'M:52-336|F:38-176',26),
    ('CKMB','CK-MB','CK-MB','BIOCHEM','U/L','Serum','yellow_sst',4,4000,'<25',27),
    ('LDH','LDH','LDH','BIOCHEM','U/L','Serum','yellow_sst',4,3000,'140-280',28),
    ('TROP_I','Troponin I','TropI','BIOCHEM','ug/L','Serum','yellow_sst',2,6000,'<0.04',29),
    ('NTBNP','NT-proBNP','NT-proBNP','BIOCHEM','pg/mL','Serum','yellow_sst',4,8000,'<125',30),
    ('CRP','C-Reactive Protein','CRP','BIOCHEM','mg/L','Serum','yellow_sst',2,2000,'<10',31),
    ('HSCRP','hs-CRP','hs-CRP','BIOCHEM','mg/L','Serum','yellow_sst',4,4000,'<1.0',32),
    ('PCT','Procalcitonin','PCT','BIOCHEM','ug/L','Serum','yellow_sst',2,7000,'<0.10',33),
    ('AMYL','Amylase','Amylase','BIOCHEM','U/L','Serum','yellow_sst',2,2500,'30-110',34),
    ('LIPASE','Lipase','Lipase','BIOCHEM','U/L','Serum','yellow_sst',2,3000,'7-60',35),
    ('LACT','Lactate','Lactate','BIOCHEM','mmol/L','Fluoride Blood','grey_fluoride',1,4000,'0.5-2.2',36),
    # HORMONES
    ('TSH','Thyroid Stimulating Hormone','TSH','HORMONE','mIU/L','Serum','yellow_sst',4,5000,'0.4-4.0',1),
    ('FT4','Free T4','fT4','HORMONE','pmol/L','Serum','yellow_sst',4,5000,'9-25',2),
    ('FT3','Free T3','fT3','HORMONE','pmol/L','Serum','yellow_sst',4,5000,'3.5-7.8',3),
    ('ANTI_TPO','Anti-TPO Antibody','Anti-TPO','HORMONE','IU/mL','Serum','yellow_sst',4,7000,'<35',4),
    ('CORT_AM','Cortisol Morning','Cortisol AM','HORMONE','nmol/L','Serum','yellow_sst',4,6000,'200-700',5),
    ('FSH','FSH','FSH','HORMONE','IU/L','Serum','yellow_sst',4,5000,'M:1-7|F:varies',6),
    ('LH','LH','LH','HORMONE','IU/L','Serum','yellow_sst',4,5000,'M:1-9|F:varies',7),
    ('PROLAC','Prolactin','Prolactin','HORMONE','mIU/L','Serum','yellow_sst',4,5000,'M:<360|F:<502',8),
    ('TESTOST','Testosterone Total','Testost','HORMONE','nmol/L','Serum','yellow_sst',4,6000,'M:10-35|F:0.7-2.8',9),
    ('E2','Estradiol','E2','HORMONE','pmol/L','Serum','yellow_sst',4,6000,'M:<180|F:varies',10),
    ('PROG','Progesterone','Prog','HORMONE','nmol/L','Serum','yellow_sst',4,6000,'Follicular:<3.2',11),
    ('INSULIN','Insulin Fasting','Insulin','HORMONE','pmol/L','Serum','yellow_sst',4,6000,'18-173',12),
    ('PTH','Parathyroid Hormone','PTH','HORMONE','pmol/L','EDTA Blood','purple_edta',4,7000,'1.6-6.9',13),
    ('VIT_D','25-OH Vitamin D','Vit D','HORMONE','nmol/L','Serum','yellow_sst',4,7000,'>50 sufficient',14),
    ('HCG_Q','Beta-hCG Quantitative','b-hCG','HORMONE','IU/L','Serum','yellow_sst',4,6000,'Non-pregnant:<5',15),
    ('IGF1','IGF-1','IGF-1','HORMONE','nmol/L','Serum','yellow_sst',4,9000,'Age-dependent',16),
    # MARKERS
    ('FERRITIN','Ferritin','Ferritin','MARKER','ug/L','Serum','yellow_sst',4,4000,'M:20-250|F:10-120',1),
    ('VIT_B12','Vitamin B12','B12','MARKER','pmol/L','Serum','yellow_sst',4,5000,'200-900',2),
    ('FOLATE','Folate Serum','Folate','MARKER','nmol/L','Serum','yellow_sst',4,5000,'7-45',3),
    ('AFP','Alpha-Fetoprotein','AFP','MARKER','ug/L','Serum','yellow_sst',4,7000,'<10',4),
    ('CEA','CEA','CEA','MARKER','ng/mL','Serum','yellow_sst',4,6000,'<5',5),
    ('PSA_T','PSA Total','PSA','MARKER','ng/mL','Serum','yellow_sst',4,7000,'<4.0',6),
    ('PSA_F','PSA Free','fPSA','MARKER','ng/mL','Serum','yellow_sst',4,5000,'ratio>25% low risk',7),
    ('CA125','CA-125','CA-125','MARKER','U/mL','Serum','yellow_sst',4,8000,'<35',8),
    ('CA199','CA 19-9','CA 19-9','MARKER','U/mL','Serum','yellow_sst',4,8000,'<37',9),
    ('CA153','CA 15-3','CA 15-3','MARKER','U/mL','Serum','yellow_sst',4,8000,'<30',10),
    ('NSE','Neuron-Specific Enolase','NSE','MARKER','ug/L','Serum','yellow_sst',4,9000,'<16.3',11),
    ('RF','Rheumatoid Factor','RF','MARKER','IU/mL','Serum','yellow_sst',4,3000,'<14',12),
    ('ANTI_CCP','Anti-CCP Antibody','Anti-CCP','MARKER','U/mL','Serum','yellow_sst',4,7000,'<7',13),
    ('ASO','ASO Titre','ASO','MARKER','IU/mL','Serum','yellow_sst',4,3000,'<200',14),
    ('ANA','Antinuclear Antibody','ANA','MARKER','titre','Serum','yellow_sst',4,7000,'Negative <1:80',15),
    # SEROLOGY
    ('HBSAG','HBsAg','HBsAg','SERO','Pos/Neg','Serum','yellow_sst',2,3000,'Negative',1),
    ('ANTI_HBS','Anti-HBs','Anti-HBs','SERO','mIU/mL','Serum','yellow_sst',2,3000,'>10 protective',2),
    ('ANTI_HCV','Anti-HCV','Anti-HCV','SERO','Pos/Neg','Serum','yellow_sst',2,4000,'Negative',3),
    ('HIV','HIV Ag/Ab Combo','HIV','SERO','Pos/Neg','Serum','yellow_sst',2,4000,'Non-reactive',4),
    ('VDRL','VDRL Syphilis Screen','VDRL','SERO','Pos/Neg','Serum','yellow_sst',2,2000,'Non-reactive',5),
    ('TPHA','TPHA Syphilis Confirm','TPHA','SERO','titre','Serum','yellow_sst',2,3000,'Non-reactive',6),
    ('HAV_IGM','Anti-HAV IgM','HAV IgM','SERO','Pos/Neg','Serum','yellow_sst',2,5000,'Negative',7),
    ('HEV_IGM','Anti-HEV IgM','HEV IgM','SERO','Pos/Neg','Serum','yellow_sst',2,5000,'Negative',8),
    ('DENGUE_NS1','Dengue NS1 Antigen','Dengue NS1','SERO','Pos/Neg','Serum','yellow_sst',2,5000,'Negative',9),
    ('DENGUE_IGM','Dengue IgM','Dengue IgM','SERO','Pos/Neg','Serum','yellow_sst',4,5000,'Negative',10),
    ('TOXO_IGM','Toxoplasma IgM','Toxo IgM','SERO','Pos/Neg','Serum','yellow_sst',4,5000,'Negative',11),
    ('RUBELLA','Rubella IgG','Rubella IgG','SERO','IU/mL','Serum','yellow_sst',4,5000,'>10 immune',12),
    ('CMV_IGM','CMV IgM','CMV IgM','SERO','Pos/Neg','Serum','yellow_sst',4,5000,'Negative',13),
    ('WIDAL','Widal Test Typhoid','Widal','SERO','titre','Serum','yellow_sst',2,2500,'O&H <1:80',14),
    # MICROBIOLOGY
    ('BLOOD_CS','Blood Culture & Sensitivity','Blood C&S','MICRO','report','Blood','red_plain',72,6000,'No growth',1),
    ('URINE_CS','Urine Culture & Sensitivity','Urine C&S','MICRO','report','MSU','urine_container',48,4000,'<10^5 CFU/mL',2),
    ('SPUT_CS','Sputum Culture & Sensitivity','Sputum C&S','MICRO','report','Sputum','other',72,4000,'No pathogens',3),
    ('GX_TB','GeneXpert MTB/RIF','GeneXpert','MICRO','report','Sputum','other',3,9000,'MTB NOT DETECTED',4),
    ('AFB_SM','AFB Sputum Smear ZN','AFB smear','MICRO','report','Sputum','other',4,3000,'Negative Grade 0',5),
    ('HP_AG','H. pylori Stool Antigen','H.pylori Ag','MICRO','Pos/Neg','Stool','stool_container',4,4000,'Negative',6),
    ('CSF_CS','CSF Culture & Sensitivity','CSF C&S','MICRO','report','CSF','other',72,7000,'No growth',7),
    ('STOOL_CS','Stool Culture & Sensitivity','Stool C&S','MICRO','report','Stool','stool_container',48,4000,'No pathogens',8),
    # URINALYSIS
    ('UA_DIP','Urine Dipstick 10-Panel','U-Dip','URINE','report','Random urine','urine_container',1,1500,'All negative/normal',1),
    ('UA_MICR','Urine Microscopy','U-Micro','URINE','report','MSU','urine_container',2,2000,'WBC<5 RBC<3/HPF',2),
    ('MICRO_ALB','Microalbuminuria ACR','Microalb','URINE','mg/mmol','Spot urine','urine_container',4,4000,'<3.0',3),
    ('UPROT','24h Urine Protein','U-Prot 24h','URINE','mg/24h','24h urine','urine_container',24,3000,'<150',4),
    ('UPCR','Urine Protein:Creatinine Ratio','UPCR','URINE','mg/mmol','Spot urine','urine_container',2,3000,'<15',5),
    ('CSF_ANA','CSF Analysis','CSF','MICRO','report','CSF','other',4,5000,'Clear Prot:15-45mg/dL',6),
]

# (test_code, flag, interpretation, significance, causes[], actions[], req_doctor_confirm, doctor_msg, doctor_urgency)
RULES = [
    ('HGB','HH','Severe polycythaemia. Hyperviscosity syndrome and thrombosis risk.','CRITICAL',
     ['Polycythaemia vera','Secondary polycythaemia (COPD, altitude)','Dehydration','Spurious (lipaemia)'],
     ['Urgent haematology consultation','Assess hyperviscosity symptoms','Check hydration & O2 saturation','Consider phlebotomy'],
     True,'Critical Hb elevation — polycythaemia/hyperviscosity risk','URGENT'),
    ('HGB','LL','Severe anaemia. Immediate risk of cardiac decompensation and organ hypoperfusion.','CRITICAL',
     ['Acute haemorrhage','Aplastic crisis','Haemolytic crisis (sickle cell, malaria, G6PD)','Severe iron deficiency'],
     ['URGENT: Notify clinician immediately','Assess transfusion criteria Hb <7 g/dL','Order reticulocytes STAT','Peripheral blood smear'],
     True,'CRITICAL Hb — urgent transfusion assessment required','IMMEDIATE'),
    ('HGB','H','Elevated haemoglobin. Possible polycythaemia or dehydration.','MODERATE',
     ['Dehydration','Polycythaemia rubra vera','COPD','Smoking','High altitude'],
     ['Assess hydration status','Check O2 saturation','Consider haematology referral if persistent'],
     False,'',''),
    ('HGB','L','Anaemia detected. Further investigation required.','MODERATE',
     ['Iron deficiency (most common)','Vitamin B12/folate deficiency','Chronic disease','Haemolysis','Thalassaemia trait'],
     ['Peripheral blood smear','Iron studies Ferritin TIBC','Vitamin B12 and Folate','Reticulocyte count'],
     False,'',''),
    ('WBC','HH','Severe leucocytosis. Possible leukaemic crisis or overwhelming infection.','CRITICAL',
     ['Acute leukaemia blast crisis','Severe bacterial sepsis','Leukaemoid reaction','CML'],
     ['IMMEDIATE clinician notification','Peripheral blood smear for blasts','Blood cultures STAT','Haematology urgent referral'],
     True,'Critical WBC elevation — leukaemia/sepsis must be excluded immediately','IMMEDIATE'),
    ('WBC','LL','Severe leucopenia. High infection risk. Possible bone marrow failure.','CRITICAL',
     ['Aplastic anaemia','Chemotherapy effect','Overwhelming sepsis','Haematological malignancy','Viral infections HIV EBV'],
     ['Isolate patient reverse barrier nursing','Blood cultures STAT','Bone marrow biopsy consideration','Haematology urgent referral'],
     True,'Critical WBC — bone marrow failure/severe sepsis must be excluded','IMMEDIATE'),
    ('WBC','H','Leucocytosis. Suggests infection, inflammation or stress response.','MODERATE',
     ['Bacterial infection','Physiological stress','Corticosteroid therapy','Inflammatory conditions','CML if very high'],
     ['Assess for infection source','CRP and Procalcitonin','Blood cultures if febrile','Differential count'],
     False,'',''),
    ('WBC','L','Leucopenia. Consider viral infection, autoimmune or drug effect.','MODERATE',
     ['Viral infections influenza HIV EBV','Drug-induced','Autoimmune disease SLE','Folate/B12 deficiency'],
     ['Differential count','Check viral screen HIV EBV','Medication review','Repeat in 2-4 weeks'],
     False,'',''),
    ('PLT','HH','Extreme thrombocytosis. Risk of thrombosis or haemorrhage.','CRITICAL',
     ['Essential thrombocythaemia','Reactive thrombocytosis','Myeloproliferative disorder','Iron deficiency'],
     ['Haematology urgent consultation','Blood film for platelet morphology','JAK2 mutation testing','Assess for thrombotic events'],
     True,'Critical platelet elevation — myeloproliferative disorder/thrombosis risk','URGENT'),
    ('PLT','LL','Severe thrombocytopenia. Significant spontaneous bleeding risk.','CRITICAL',
     ['Immune thrombocytopenia ITP','DIC','Drug-induced heparin quinine','Bone marrow failure','Malaria','Dengue'],
     ['Immediate clinician notification','Coagulation screen PT aPTT Fibrinogen D-Dimer','Blood film review','Consider platelet transfusion if <10'],
     True,'CRITICAL platelets — spontaneous bleeding risk urgent clinical review','IMMEDIATE'),
    ('PLT','H','Thrombocytosis. Usually reactive.','LOW',
     ['Reactive infection inflammation iron deficiency post-splenectomy','Essential thrombocythaemia','CML'],
     ['Assess for underlying cause','CRP/ESR','Iron studies','Repeat if persistently elevated'],
     False,'',''),
    ('PLT','L','Mild-moderate thrombocytopenia. Monitor for bleeding.','MODERATE',
     ['ITP','Drug-induced','Viral infection','Hypersplenism','Liver disease'],
     ['Peripheral blood smear','Medication review','LFT if liver disease suspected','Repeat to confirm'],
     False,'',''),
    ('MCV','H','Macrocytosis. Megaloblastic causes most common.','MODERATE',
     ['Vitamin B12 deficiency','Folate deficiency','Liver disease alcoholism','Hypothyroidism','Haemolysis','Drug effect'],
     ['Vitamin B12 and Folate levels','LFT and GGT alcohol','TSH','Reticulocyte count','PBS for hypersegmented neutrophils'],
     False,'',''),
    ('MCV','L','Microcytosis. Iron deficiency most common in Rwanda.','MODERATE',
     ['Iron deficiency anaemia','Thalassaemia trait alpha or beta','Anaemia of chronic disease','Sideroblastic anaemia'],
     ['Ferritin and TIBC/iron studies','Haemoglobin electrophoresis if thalassaemia suspected','PBS','Reticulocyte count'],
     False,'',''),
    ('ESR','HH','Markedly elevated ESR >100 mm/h. Serious pathology must be excluded.','HIGH',
     ['Multiple myeloma commonest cause of very high ESR','Temporal arteritis/vasculitis','Severe sepsis','Advanced malignancy','Chronic infection TB osteomyelitis'],
     ['Protein electrophoresis myeloma screen','CRP/Procalcitonin','Blood cultures if febrile','GeneXpert/AFB smear TB screen','Haematology/Oncology referral'],
     True,'ESR >100 mm/h — serious pathology myeloma/vasculitis/TB requires exclusion','URGENT'),
    ('ESR','H','Elevated ESR. Non-specific marker of inflammation.','MODERATE',
     ['Infection bacterial TB','Inflammatory arthritis RA SLE','Anaemia','Malignancy','Pregnancy'],
     ['CRP more specific','Full blood count','Review for autoimmune/infection signs'],
     False,'',''),
    ('RETIC','HH','Markedly elevated reticulocyte count. Active haemolysis or haemorrhage.','HIGH',
     ['Haemolytic anaemia SCD crisis G6PD malaria','Post-haemorrhagic response','Post-treatment response iron B12 folate'],
     ['Peripheral blood smear','Bilirubin indirect','LDH haemolysis marker','Direct Coombs test','Malaria screen'],
     False,'',''),
    ('RETIC','L','Low reticulocyte count. Inadequate bone marrow response.','MODERATE',
     ['Aplastic anaemia','Iron/B12/folate deficiency untreated','Bone marrow infiltration','Chronic renal failure EPO deficiency'],
     ['Bone marrow biopsy consideration','Iron studies B12 folate','Renal function creatinine eGFR','Haematology referral'],
     False,'',''),
    ('PT','H','Prolonged PT. Coagulation pathway impairment.','HIGH',
     ['Warfarin/anticoagulant therapy','Liver disease','Vitamin K deficiency','DIC'],
     ['INR calculation','LFT liver disease','Medication review anticoagulants','DIC screen if clinically indicated'],
     False,'',''),
    ('PT','HH','Critically prolonged PT. Severe haemorrhage risk.','CRITICAL',
     ['DIC','Severe liver failure','Massive anticoagulant overdose','Massive blood transfusion'],
     ['IMMEDIATE clinician notification','DIC screen fibrinogen D-dimer platelets','Consider FFP/Vitamin K','Stop offending drugs'],
     True,'Critical PT prolongation — bleeding risk urgent clinical review','IMMEDIATE'),
    ('INR','HH','INR critically elevated. Life-threatening bleeding risk.','CRITICAL',
     ['Warfarin overdose','Severe hepatic failure','DIC','Rodenticide poisoning'],
     ['Immediate clinician notification','Vitamin K administration consideration','Consider FFP/4-factor PCC','Stop warfarin urgent reversal'],
     True,'Critical INR — severe bleeding risk urgent reversal required','IMMEDIATE'),
    ('APTT','H','Prolonged aPTT. Intrinsic pathway or common pathway defect.','MODERATE',
     ['Heparin therapy','Factor VIII/IX/XI/XII deficiency','Haemophilia A or B','Lupus anticoagulant','Von Willebrand disease'],
     ['Mixing studies','Factor assays if haemophilia suspected','Lupus anticoagulant screen','Medication review heparin'],
     False,'',''),
    ('APTT','HH','Critically prolonged aPTT. Haemorrhage or DIC risk.','CRITICAL',
     ['Heparin overdose','DIC','Severe haemophilia','Acquired haemophilia anti-factor VIII'],
     ['Immediate clinician notification','DIC screen','Anti-Xa level if on heparin','Haematology urgent consultation'],
     True,'Critical aPTT — haemorrhage risk urgent clinical review','IMMEDIATE'),
    ('DDIMER','H','Elevated D-dimer. Fibrin degradation occurring.','HIGH',
     ['Venous thromboembolism PE/DVT commonest serious cause','DIC','Recent surgery/trauma','Infection/sepsis','Malignancy','Pregnancy'],
     ['Wells score clinical probability assessment','CT pulmonary angiogram if PE suspected','Lower limb Doppler USS if DVT suspected','DIC screen if coagulopathy'],
     True,'Elevated D-dimer — PE/DVT must be excluded clinically and radiologically','URGENT'),
    ('FIBRIN','LL','Low fibrinogen. Consumption or production failure.','HIGH',
     ['DIC consumptive coagulopathy','Severe liver failure','Massive transfusion','Thrombolytic therapy'],
     ['DIC screen PT aPTT D-dimer platelets','LFT','Clinician notification for bleeding risk','Consider cryoprecipitate replacement'],
     True,'Low fibrinogen — DIC or severe liver disease must be excluded','URGENT'),
    ('FBG','HH','Severe hyperglycaemia. Diabetic emergency DKA/HHS must be excluded.','CRITICAL',
     ['Diabetic ketoacidosis DKA','Hyperosmolar hyperglycaemic state HHS','New-onset diabetes','Stress hyperglycaemia'],
     ['Immediate clinician notification','Urine/blood ketones DKA vs HHS','Blood gas acidosis','Electrolytes K+ critical in DKA','IV insulin and fluid resuscitation'],
     True,'Critical blood glucose — diabetic emergency DKA/HHS must be excluded immediately','IMMEDIATE'),
    ('FBG','LL','Severe hypoglycaemia. Neurological damage and death risk.','CRITICAL',
     ['Insulin overdose most common','Oral hypoglycaemic overdose sulphonylureas','Insulinoma','Addisons disease','Severe liver failure','Alcohol toxicity'],
     ['IMMEDIATE 50% dextrose IV if unconscious oral glucose if conscious','Notify clinician immediately','Fasting insulin and C-peptide','Cortisol Addisons exclusion','Monitor glucose 15-minutely'],
     True,'Critical hypoglycaemia — immediate glucose administration required','IMMEDIATE'),
    ('FBG','H','Elevated fasting glucose. Prediabetes or diabetes requires assessment.','MODERATE',
     ['Type 2 diabetes mellitus','Prediabetes impaired fasting glucose','Gestational diabetes','Steroid-induced hyperglycaemia'],
     ['HbA1c for glycaemic control assessment','Repeat fasting glucose confirm diagnosis','Urine glucose and protein','Consider OGTT if prediabetes suspected'],
     False,'',''),
    ('FBG','L','Fasting hypoglycaemia. Insulin excess or adrenal insufficiency.','HIGH',
     ['Insulin or sulphonylurea overdose','Insulinoma','Addisons disease','Reactive hypoglycaemia','Alcohol hypoglycaemia'],
     ['Fasting insulin and C-peptide simultaneous','Cortisol Addisons exclusion','Liver function tests','Endocrinology referral if recurrent'],
     True,'Hypoglycaemia — insulinoma/adrenal insufficiency requires exclusion','URGENT'),
    ('CREAT','HH','Critically elevated creatinine. AKI or CKD with dialysis consideration.','CRITICAL',
     ['AKI pre-renal dehydration sepsis renal GN ATN post-renal obstruction','End-stage CKD','Rhabdomyolysis','Nephrotoxic drugs NSAIDs aminoglycosides contrast'],
     ['Immediate clinician notification','Urea and electrolytes K+ critical','Bicarbonate acidosis','Urine output monitoring','Renal ultrasound','Nephrology urgent consultation','Consider dialysis'],
     True,'Critical creatinine — AKI/end-stage CKD dialysis consideration required','IMMEDIATE'),
    ('CREAT','H','Elevated creatinine. Renal impairment requiring clinical assessment.','HIGH',
     ['CKD commonest cause','AKI dehydration drugs obstruction','Rhabdomyolysis','Pre-renal azotaemia'],
     ['eGFR calculation','Urine analysis and microscopy','Electrolytes K+ HCO3-','Renal ultrasound','Medication review nephrotoxins'],
     False,'',''),
    ('K','HH','Critical hyperkalaemia. Cardiac arrest risk.','CRITICAL',
     ['Renal failure K+ retention','Rhabdomyolysis','Metabolic acidosis','Addisons disease','ACE inhibitor K-sparing diuretic overdose','Pseudohyperkalaemia haemolysed sample'],
     ['IMMEDIATE clinician notification ECG changes may be present','12-lead ECG stat','IV calcium gluconate cardiac membrane stabilisation','Insulin/dextrose K shift','Consider dialysis','Repeat sample to exclude pseudohyperkalaemia'],
     True,'Critical K+ — cardiac arrest imminent IMMEDIATE intervention required','IMMEDIATE'),
    ('K','LL','Critical hypokalaemia. Life-threatening arrhythmia risk.','CRITICAL',
     ['Vomiting/diarrhoea GI losses','Diuretic excess furosemide thiazides','Hyperaldosteronism','Refeeding syndrome','DKA treatment K+ shifts intracellularly','Hypomagnesaemia'],
     ['IMMEDIATE clinician notification','12-lead ECG U waves QT prolongation','Magnesium level treat if low K+ repletion fails without Mg2+','IV/oral potassium replacement','Monitor continuously'],
     True,'Critical K+ — life-threatening arrhythmia risk immediate replacement required','IMMEDIATE'),
    ('K','H','Hyperkalaemia. Renal function must be assessed.','HIGH',
     ['Renal impairment','ACE inhibitors/ARBs','Metabolic acidosis','Excessive K+ supplementation','Addisons disease'],
     ['Renal function creatinine urea','Repeat sample exclude haemolysis','ECG if K+ >6.0','Review medications','Dietary review'],
     False,'',''),
    ('K','L','Hypokalaemia. GI losses and diuretics most common.','MODERATE',
     ['Diuretic therapy furosemide thiazides','Vomiting or diarrhoea','Inadequate dietary intake','Refeeding syndrome'],
     ['Magnesium level often co-depleted','Renal function','Dietary assessment','Oral potassium supplementation','Medication review'],
     False,'',''),
    ('NA','HH','Critical hypernatraemia. Risk of CNS damage cerebral dehydration.','CRITICAL',
     ['Severe dehydration','Diabetes insipidus central or nephrogenic','Excessive hypertonic saline','Hyperaldosteronism'],
     ['Immediate clinician notification','Urine osmolality and sodium','Fluid status assessment','Slow correction with hypotonic fluids avoid rapid correction','Vasopressin if DI'],
     True,'Critical Na+ — CNS damage risk slow controlled correction required','IMMEDIATE'),
    ('NA','LL','Critical hyponatraemia. Seizure and coma risk.','CRITICAL',
     ['SIADH most common drugs CNS disease malignancy pneumonia','Hypovolaemic hyponatraemia GI losses diuretics','Hypothyroidism','Addisons disease','Psychogenic polydipsia','Heart failure cirrhosis dilutional'],
     ['Immediate clinician notification','Urine sodium and osmolality SIADH vs other','Cortisol Addisons exclusion','TSH hypothyroidism','Slow correction target <10 mmol/L/24h osmotic demyelination risk'],
     True,'Critical Na+ — seizure/coma risk slow controlled correction required','IMMEDIATE'),
    ('NA','H','Hypernatraemia. Usually dehydration.','MODERATE',
     ['Dehydration fever inadequate intake','Diabetes insipidus','Excessive sodium intake'],
     ['Fluid status assessment','Urine osmolality','Renal function','Gentle rehydration'],
     False,'',''),
    ('NA','L','Hyponatraemia. Common electrolyte abnormality.','MODERATE',
     ['SIADH','Diuretic therapy','Hypothyroidism','Adrenal insufficiency','Dilutional heart failure cirrhosis nephrotic syndrome'],
     ['Urine sodium and osmolality identify SIADH','TSH','Short Synacthen test if Addisons suspected','Medication review','Fluid restriction if SIADH'],
     False,'',''),
    ('CA','HH','Critical hypercalcaemia. Cardiac and neurological emergency.','CRITICAL',
     ['Malignancy commonest bone metastases PTHrP','Primary hyperparathyroidism','Sarcoidosis','Vitamin D toxicity','Immobilisation'],
     ['Immediate clinician notification','IV hydration normal saline','PTH level','Bisphosphonates consideration','Malignancy workup','ECG short QTc'],
     True,'Critical Ca2+ — cardiac arrhythmia and coma risk immediate IV hydration required','IMMEDIATE'),
    ('CA','LL','Critical hypocalcaemia. Tetany and cardiac risk.','CRITICAL',
     ['Post-thyroidectomy/parathyroidectomy hypoparathyroidism','Vitamin D deficiency severe','Acute pancreatitis','Hypomagnesaemia','Malabsorption','Renal failure'],
     ['Immediate clinician notification Chvosteks and Trousseaus signs','IV calcium gluconate if symptomatic','PTH level','Vitamin D 25-OH','Magnesium level','ECG prolonged QTc'],
     True,'Critical Ca2+ — tetany and cardiac risk urgent IV calcium may be needed','IMMEDIATE'),
    ('ALT','HH','Critically elevated ALT >10x ULN. Acute hepatocellular damage.','CRITICAL',
     ['Acute viral hepatitis A B C E','Drug-induced liver injury paracetamol anti-TB statins','Ischaemic hepatitis shock liver','Acute Budd-Chiari','Wilsons disease'],
     ['Urgent clinician notification','Hepatitis serology HBsAg Anti-HCV HAV IgM HEV IgM','Paracetamol level','INR/PT synthetic function','Abdominal ultrasound','Hepatology consultation'],
     True,'Critical ALT — acute hepatocellular damage hepatitis serology urgent','URGENT'),
    ('ALT','H','Elevated ALT. Hepatocellular inflammation or injury.','MODERATE',
     ['NAFLD commonest','Alcohol-related liver disease','Chronic viral hepatitis B or C','Drug effect','Autoimmune hepatitis'],
     ['HBsAg and Anti-HCV','GGT alcohol marker','Abdominal ultrasound fatty liver','ANA and anti-smooth muscle Ab','Medication review'],
     False,'',''),
    ('AST','HH','Critically elevated AST. Acute hepatic or myocardial necrosis.','CRITICAL',
     ['Acute hepatitis viral drug ischaemic','Myocardial infarction AMI','Rhabdomyolysis','Acute liver failure'],
     ['ALT:AST ratio >2:1 suggests alcohol <1 suggests myocardial','CK and Troponin I cardiac/muscle','Hepatitis serology','ECG','LFT panel'],
     True,'Critical AST — acute liver/cardiac/muscle necrosis must be differentiated urgently','URGENT'),
    ('ALP','H','Elevated ALP. Cholestatic liver disease or bone pathology.','MODERATE',
     ['Cholestasis biliary obstruction PBC PSC','Bone disease Pagets metastases fracture rickets','Pregnancy placental ALP','Drug-induced cholestasis'],
     ['GGT if elevated confirms hepatic source','Bilirubin and other LFTs','Bone-specific ALP if bone suspected','Abdominal ultrasound','Bone profile Ca PO4'],
     False,'',''),
    ('TBIL','HH','Critical hyperbilirubinaemia. Acute liver failure or haemolytic crisis.','CRITICAL',
     ['Acute liver failure','Severe haemolytic anaemia crisis','Crigler-Najjar syndrome','Acute biliary obstruction with cholangitis'],
     ['Immediate clinician notification','Direct vs indirect bilirubin','LFT panel and INR','Blood film and haemolysis markers LDH Coombs','Abdominal ultrasound biliary obstruction'],
     True,'Critical bilirubin — acute liver failure or haemolytic crisis requires urgent assessment','URGENT'),
    ('TBIL','H','Jaundice-level bilirubin. Clinical assessment required.','HIGH',
     ['Hepatitis viral alcoholic drug','Biliary obstruction gallstones cholangiocarcinoma pancreatic cancer','Haemolytic anaemia','Gilberts syndrome mild benign'],
     ['Direct bilirubin conjugated vs unconjugated','LFT panel','Hepatitis serology','Abdominal ultrasound','Blood film if haemolysis suspected'],
     False,'',''),
    ('TCHOL','H','Elevated total cholesterol. Cardiovascular risk assessment required.','MODERATE',
     ['Familial hypercholesterolaemia','Secondary hyperlipidaemia hypothyroidism nephrotic syndrome DM','Dietary high saturated fat','Sedentary lifestyle'],
     ['Fasting lipid profile LDL HDL TG','TSH hypothyroidism','Renal function and urine protein','Cardiovascular risk scoring Framingham','Dietary and lifestyle advice'],
     False,'',''),
    ('TG','HH','Critical hypertriglyceridaemia. Acute pancreatitis risk.','CRITICAL',
     ['Familial hypertriglyceridaemia','Uncontrolled diabetes DKA/HHS','Alcohol excess','Hypothyroidism','Renal failure','Drug-induced steroids retinoids antipsychotics'],
     ['Immediate clinician notification','Assess for acute pancreatitis amylase lipase clinical','Blood glucose and HbA1c','TSH','Fibrate therapy consideration','Strict dietary restriction'],
     True,'TG critically elevated — acute pancreatitis risk urgent clinical assessment','URGENT'),
    ('TROP_I','H','Elevated Troponin I. Myocardial injury until proven otherwise.','CRITICAL',
     ['Acute myocardial infarction STEMI/NSTEMI commonest serious cause','Myocarditis','Pulmonary embolism right heart strain','Cardiac contusion','Sepsis-related myocardial injury','Renal failure impaired clearance'],
     ['IMMEDIATE clinician notification','12-lead ECG stat','Serial Troponin at 3h and 6h rising confirms AMI','CK-MB','Cardiology urgent consultation','Aspirin and heparin per protocol if AMI confirmed'],
     True,'Elevated Troponin I — ACUTE MYOCARDIAL INFARCTION must be excluded immediately','IMMEDIATE'),
    ('TROP_I','HH','Critically elevated Troponin. Active myocardial infarction likely.','CRITICAL',
     ['STEMI/NSTEMI massive infarct','Fulminant myocarditis','Cardiogenic shock'],
     ['IMMEDIATE cardiology activation','12-lead ECG STEMI Cath Lab activation','Aspirin LMWH loading antiplatelet','Serial ECG monitoring','ICU level care'],
     True,'CRITICAL Troponin — MASSIVE AMI likely ACTIVATE CARDIAC CATHETERISATION LAB','IMMEDIATE'),
    ('NTBNP','H','Elevated NT-proBNP. Heart failure or cardiac stress.','HIGH',
     ['Heart failure most specific use','Acute coronary syndrome','Pulmonary hypertension','Renal failure impaired clearance','Atrial fibrillation'],
     ['Clinician notification','Echocardiogram','Chest X-ray pulmonary oedema','Renal function','Cardiology referral'],
     True,'Elevated NT-proBNP — heart failure must be excluded clinically','URGENT'),
    ('CRP','HH','Critically elevated CRP. Severe infection or major inflammatory process.','HIGH',
     ['Severe bacterial infection/sepsis','Bacterial endocarditis','Osteomyelitis','Major trauma/burns','Vasculitis'],
     ['Blood cultures STAT','Procalcitonin sepsis marker','Full blood count with differential','Identify infection source','Consider sepsis protocol'],
     True,'CRP >200 mg/L — severe bacterial infection/sepsis likely blood cultures urgently required','URGENT'),
    ('CRP','H','Elevated CRP. Active inflammation or infection.','MODERATE',
     ['Bacterial infection','Viral infection','Inflammatory arthritis','Inflammatory bowel disease','Post-surgical'],
     ['Full blood count','ESR','Procalcitonin if sepsis suspected','Identify source of inflammation','Blood cultures if febrile'],
     False,'',''),
    ('PCT','HH','Procalcitonin critically elevated. Severe bacterial sepsis or septic shock.','CRITICAL',
     ['Gram-negative sepsis','Septic shock multiorgan failure','Bacterial endocarditis','Severe community-acquired pneumonia bacterial'],
     ['Immediate sepsis protocol activation Surviving Sepsis Campaign bundles','Blood cultures x2 STAT','IV broad-spectrum antibiotics within 1 hour','Lactate level','ICU referral'],
     True,'Critical PCT — SEPTIC SHOCK must be assumed immediate antibiotic therapy required','IMMEDIATE'),
    ('PCT','H','Elevated PCT. Bacterial infection likely.','HIGH',
     ['Bacterial pneumonia','Urinary tract infection complicated','Intra-abdominal infection','Bacterial meningitis'],
     ['Cultures blood urine sputum before antibiotics','CRP and WBC','Identify focus of infection','Antibiotic therapy guided by sensitivity'],
     True,'Elevated PCT — significant bacterial infection antibiotic therapy likely required','URGENT'),
    ('TSH','HH','Grossly elevated TSH. Severe hypothyroidism.','HIGH',
     ['Primary hypothyroidism Hashimotos thyroiditis post-RAI post-thyroidectomy','Non-compliance with levothyroxine','Recovery from thyroiditis'],
     ['FT4 confirm hypothyroidism','Anti-TPO antibodies Hashimotos','Prolactin','Endocrinology referral if very high','Levothyroxine therapy initiation or dose increase'],
     True,'TSH >20 mIU/L — significant hypothyroidism endocrinology review recommended','URGENT'),
    ('TSH','LL','Suppressed TSH. Hyperthyroidism or over-replacement.','HIGH',
     ['Graves disease autoimmune hyperthyroidism','Toxic multinodular goitre','Toxic adenoma','Excessive levothyroxine dose','Subacute thyroiditis','Amiodarone-induced thyrotoxicosis'],
     ['FT4 and FT3 confirm thyrotoxicosis','TSH receptor antibodies TRAb for Graves disease','Thyroid uptake scan if etiology unclear','Endocrinology referral','Antithyroid drugs or beta-blockers if symptomatic'],
     True,'Suppressed TSH — hyperthyroidism must be confirmed and managed','URGENT'),
    ('PROLAC','HH','Grossly elevated prolactin. Prolactinoma likely.','HIGH',
     ['Prolactinoma pituitary adenoma commonest cause of very high levels','Drug-induced antipsychotics metoclopramide domperidone','Hypothyroidism','Macroprolactinaemia benign'],
     ['Pituitary MRI mandatory if >200 IU/L','TSH hypothyroidism','Medication review','Macroprolactin measurement','Endocrinology referral'],
     True,'Markedly elevated prolactin — prolactinoma highly likely MRI pituitary required','URGENT'),
    ('CORT_AM','LL','Low morning cortisol. Adrenal insufficiency must be excluded.','CRITICAL',
     ['Primary adrenal insufficiency Addisons disease','Secondary adrenal insufficiency pituitary','Long-term steroid therapy HPA axis suppression','Adrenal crisis'],
     ['Urgent clinician notification Addisonian crisis risk','Short Synacthen test gold standard','ACTH level high primary low secondary','Electrolytes hyponatraemia hyperkalaemia in Addisons','Hydrocortisone if clinical adrenal crisis'],
     True,'Low cortisol — adrenal insufficiency/Addisonian crisis must be excluded urgently','URGENT'),
    ('VIT_D','LL','Severe vitamin D deficiency. Risk of osteomalacia and immune dysfunction.','HIGH',
     ['Insufficient sun exposure commonest in Rwanda','Dietary deficiency','Malabsorption coeliac disease Crohns','Chronic liver or kidney disease','Obesity','Anticonvulsant therapy'],
     ['Calcium and PTH secondary hyperparathyroidism','Phosphate low in osteomalacia','ALP elevated in osteomalacia','High-dose vitamin D supplementation','Dietary advice','Repeat level after 3 months treatment'],
     False,'',''),
    ('VIT_D','L','Vitamin D insufficiency. Supplementation recommended.','LOW',
     ['Insufficient sun exposure','Dietary deficiency','Sedentary indoor lifestyle'],
     ['Calcium and PTH','Dietary advice','Moderate-dose vitamin D supplementation'],
     False,'',''),
    ('FERRITIN','LL','Severely depleted iron stores. Definitive diagnosis of iron deficiency.','HIGH',
     ['Iron deficiency dietary commonest in Rwanda','Chronic blood loss GI colorectal cancer ulcer hookworm gynaecological menorrhagia','Malabsorption coeliac disease','Pregnancy increased demand'],
     ['TIBC and serum iron iron saturation <20% confirms deficiency','FBC microcytic anaemia','Stool occult blood exclude GI bleeding','Colonoscopy if >50y or anaemia unexplained','Iron supplementation therapy'],
     False,'',''),
    ('FERRITIN','HH','Markedly elevated ferritin. Haemochromatosis liver disease or HLH.','HIGH',
     ['Hereditary haemochromatosis','Liver disease alcohol cirrhosis ferritin is an acute phase reactant','Adult-onset Stills disease','Haemophagocytic lymphohistiocytosis HLH very high levels','Multiple blood transfusions'],
     ['LFT liver disease','Iron studies transferrin saturation','HFE gene mutation testing haemochromatosis','Bone marrow biopsy if HLH suspected','Venesection for haemochromatosis'],
     True,'Very high ferritin — haemochromatosis or haemophagocytic syndrome requires urgent investigation','URGENT'),
    ('VIT_B12','LL','Vitamin B12 deficiency. Risk of megaloblastic anaemia and neurological damage.','HIGH',
     ['Pernicious anaemia autoimmune intrinsic factor deficiency commonest in adults','Vegan/vegetarian diet','Gastric surgery or chronic metformin use','Malabsorption terminal ileal disease Crohns','Alcoholism'],
     ['PBS hypersegmented neutrophils macro-ovalocytes','MCV macrocytosis','Folate combined deficiency','Intrinsic factor antibodies pernicious anaemia','IM B12 replacement'],
     False,'',''),
    ('AFP','H','Elevated AFP. Hepatocellular carcinoma or germ cell tumour must be excluded.','HIGH',
     ['Hepatocellular carcinoma HCC major cause','Testicular germ cell tumours non-seminoma','Hepatitis B/C with cirrhosis','Pregnancy normal in second trimester','Benign liver disease hepatitis cirrhosis moderate elevation'],
     ['Urgent clinician notification','HBsAg and Anti-HCV HCC risk factors','Abdominal ultrasound liver lesions','CT liver with contrast characterise lesion','AFP trending rising = concern','Hepatology/Oncology referral'],
     True,'Elevated AFP — hepatocellular carcinoma must be excluded urgently','URGENT'),
    ('PSA_T','H','Elevated PSA. Prostate cancer BPH or prostatitis.','HIGH',
     ['Prostate cancer >50% probability if PSA >10','Benign prostatic hyperplasia BPH','Prostatitis acute bacterial very high PSA','After DRE or biopsy transient','UTI'],
     ['Free PSA ratio fPSA/tPSA <10% strongly suggests cancer','Digital rectal examination DRE','Urology referral for biopsy consideration','MRI prostate multiparametric','PSA velocity rate of rise over time'],
     True,'PSA elevated — prostate cancer requires clinical and radiological exclusion','URGENT'),
    ('CA125','H','Elevated CA-125. Ovarian pathology must be assessed in women.','HIGH',
     ['Ovarian cancer epithelial commonest cause in postmenopausal women','Endometriosis','Pelvic inflammatory disease','Pregnancy','Benign ovarian cysts','Liver disease heart failure'],
     ['Urgent clinician notification','Pelvic ultrasound transvaginal','CT pelvis and abdomen if malignancy suspected','HE4 more specific for ovarian cancer','Gynaecology/Oncology referral'],
     True,'Elevated CA-125 — ovarian malignancy must be excluded in postmenopausal women','URGENT'),
    ('ANTI_CCP','H','Elevated Anti-CCP. Highly specific for Rheumatoid Arthritis.','HIGH',
     ['Rheumatoid arthritis 95% specific positive years before clinical symptoms','Pre-clinical RA','RA with seronegative RF'],
     ['RF if not done','ESR/CRP','Joint X-rays erosions','DAS28 score assessment','Rheumatology referral for DMARD therapy','Methotrexate consideration'],
     True,'Anti-CCP positive — Rheumatoid Arthritis diagnosis strongly supported rheumatology referral required','URGENT'),
    ('ASO','H','Elevated ASO titre. Recent streptococcal infection. Rheumatic fever risk.','MODERATE',
     ['Recent Group A streptococcal pharyngitis','Acute rheumatic fever ARF','Post-streptococcal glomerulonephritis'],
     ['Clinical assessment for ARF Jones criteria carditis arthritis chorea skin changes','ECG PR interval prolongation in ARF','Throat swab culture','Echocardiogram rheumatic valvular disease','Penicillin prophylaxis if ARF confirmed'],
     True,'Elevated ASO — rheumatic fever must be excluded clinically Jones criteria','URGENT'),
    ('HBSAG','POS','Positive HBsAg. Active hepatitis B infection acute or chronic.','HIGH',
     ['Acute Hepatitis B HBsAg positive <6 months','Chronic Hepatitis B HBsAg positive >6 months','Perinatal transmission','Sexual transmission','Blood-borne transmission'],
     ['Urgent clinician notification','HBeAg and Anti-HBe viral replication status','HBV DNA viral load guides treatment','LFT panel liver damage','Abdominal ultrasound cirrhosis HCC','Hepatology referral','Vaccination of household contacts'],
     True,'HBsAg POSITIVE — Hepatitis B infection confirmed urgent hepatology referral and contact tracing','URGENT'),
    ('ANTI_HCV','POS','Reactive Anti-HCV. Hepatitis C exposure detected.','HIGH',
     ['Acute or chronic Hepatitis C infection','Prior resolved infection Anti-HCV persists after clearance','Blood-borne transmission IVDU transfusion needlestick','Sexual transmission less efficient'],
     ['Urgent clinician notification','HCV RNA PCR confirms active infection negative RNA = resolved','LFT panel','Abdominal ultrasound cirrhosis','Hepatitis C genotype guides treatment','Hepatology referral for DAA therapy','Contact tracing'],
     True,'Anti-HCV REACTIVE — Hepatitis C confirmed or exposed HCV RNA PCR urgently required','URGENT'),
    ('HIV','POS','HIV Ag/Ab Reactive. HIV infection must be confirmed.','CRITICAL',
     ['HIV-1 infection most common in Rwanda','HIV-2 infection','Early acute HIV window period','False positive rare repeat required'],
     ['Immediate clinician notification with sensitivity and counselling','Confirmatory HIV test different platform or Western Blot','CD4 count and HIV viral load disease staging','STI screen VDRL HBsAg Anti-HCV','TB screening GeneXpert CXR','ART initiation counselling','Partner testing and contact notification'],
     True,'HIV REACTIVE — confirmed positive requires immediate counselling and ART initiation workup','IMMEDIATE'),
    ('VDRL','POS','VDRL Reactive. Syphilis or biological false positive.','HIGH',
     ['Syphilis Treponema pallidum infection all stages','Biological false positive SLE antiphospholipid syndrome pregnancy malaria viral infections'],
     ['Clinician notification','TPHA/TPPA treponemal confirmatory test','HIV test co-infection common','Clinical staging primary/secondary/tertiary','Benzathine penicillin treatment','Partner notification and treatment'],
     True,'VDRL REACTIVE — syphilis must be confirmed with treponemal test and treated','URGENT'),
    ('DENGUE_NS1','POS','Positive Dengue NS1 Antigen. Active early dengue infection.','HIGH',
     ['Dengue fever DENV 1-4','Highest sensitivity in first 5 days of illness'],
     ['Clinician notification','FBC thrombocytopenia classic finding','LFT transaminase elevation','Haematocrit haemoconcentration in dengue haemorrhagic fever','Monitor warning signs abdominal pain rapid breathing bleeding','Dengue IgM/IgG at day 5+ for confirmation','Supportive management IV fluids if severe'],
     True,'Dengue NS1 POSITIVE — active dengue confirmed monitor closely for haemorrhagic complications','URGENT'),
    ('MAL_RDT','POS','Positive Malaria RDT. Active malaria infection confirmed.','CRITICAL',
     ['Plasmodium falciparum most common and dangerous in Rwanda','Plasmodium vivax','Plasmodium malariae','Plasmodium ovale'],
     ['Immediate clinician notification','Malaria blood smear thin and thick species confirmation and parasitaemia quantification','FBC haemolytic anaemia thrombocytopenia','Glucose hypoglycaemia in falciparum malaria','Renal function cerebral malaria','Artemether-lumefantrine per Rwanda malaria treatment guidelines','IV artesunate if severe/cerebral malaria'],
     True,'Malaria RDT POSITIVE — IMMEDIATE antimalarial treatment required per national guidelines','IMMEDIATE'),
    ('GX_TB','H','GeneXpert MTB Detected. Active tuberculosis confirmed.','CRITICAL',
     ['Pulmonary TB most common','Extrapulmonary TB lymph node pleural meningeal miliary'],
     ['Immediate clinician notification','Rifampicin resistance result if Rif-R MDR-TB protocol','CXR','HIV test co-infection mandatory','LFT baseline before anti-TB drugs','Weight measurement','National TB programme notification and contact tracing','2HRZE + 4HR standard TB treatment if Rif-sensitive'],
     True,'GeneXpert MTB DETECTED — Tuberculosis confirmed immediate treatment initiation required','IMMEDIATE'),
    ('UA_DIP','H','Abnormal urine dipstick. Multiple parameters require assessment.','MODERATE',
     ['Proteinuria glomerulonephritis nephrotic syndrome hypertensive nephropathy diabetic nephropathy','Glucosuria diabetes mellitus','Haematuria UTI renal stones bladder cancer glomerulonephritis','Leucocyturia plus nitrites UTI'],
     ['Urine microscopy confirm cellular elements','Urine culture and sensitivity if leucocytes/nitrites','Fasting blood glucose if glucosuria','Renal function and eGFR if proteinuria','Urine protein:creatinine ratio if proteinuria','Renal ultrasound haematuria'],
     False,'',''),
    ('MICRO_ALB','H','Elevated urine albumin:creatinine ratio. Early diabetic or hypertensive nephropathy.','HIGH',
     ['Diabetic nephropathy earliest sign of renal involvement','Hypertensive nephropathy','Glomerulonephritis','Cardiovascular risk marker'],
     ['Blood glucose and HbA1c diabetic control','Blood pressure assessment','Renal function and eGFR','Repeat ACR x2 more samples to confirm two of three positive','ACE inhibitor/ARB therapy initiation renoprotective','Nephrology referral if >300 mg/mmol'],
     True,'Elevated microalbuminuria — diabetic/hypertensive nephropathy ACE inhibitor therapy should be considered','URGENT'),
    ('CSF_ANA','H','Abnormal CSF. Meningitis or intracranial pathology.','CRITICAL',
     ['Bacterial meningitis high protein low glucose PMN pleocytosis','Viral meningitis lymphocytic pleocytosis normal glucose','TB meningitis lymphocytic very low glucose very high protein','Cryptococcal meningitis India ink positive CD4 low in HIV','Subarachnoid haemorrhage xanthochromia RBCs'],
     ['Immediate clinician notification','CSF Gram stain and culture bacteria','CSF India ink and cryptococcal antigen HIV patients','CSF AFB smear and GeneXpert TB meningitis','Blood cultures simultaneously','IV antibiotics immediately if bacterial meningitis suspected','Dexamethasone bacterial meningitis'],
     True,'Abnormal CSF — meningitis/CNS infection requires IMMEDIATE empirical treatment','IMMEDIATE'),
]

# (trigger_code, trigger_flag, suggested_code, type, reason, dept, note_to_doctor)
REFLEX = [
    ('HGB','LL','RETIC','MANDATORY','Assess bone marrow response to severe anaemia','Hematology','Reticulocyte count STAT'),
    ('HGB','LL','PBS','MANDATORY','RBC morphology for anaemia classification and haemolysis exclusion','Hematology','PBS to identify sickle cells fragmented RBCs blasts parasites'),
    ('HGB','LL','FERRITIN','RECOMMENDED','Iron deficiency is the commonest cause of severe anaemia in Rwanda','Marker','Ferritin distinguishes iron deficiency from other causes'),
    ('HGB','L','FERRITIN','MANDATORY','Iron studies mandatory for anaemia workup','Marker','Ferritin is the single best test for iron stores'),
    ('HGB','L','VIT_B12','RECOMMENDED','Megaloblastic anaemia must be excluded','Marker','B12 deficiency causes macrocytic anaemia with neurological complications'),
    ('HGB','L','FOLATE','RECOMMENDED','Folate deficiency causes megaloblastic anaemia especially in pregnancy','Marker','Folate particularly important in pregnant patients'),
    ('HGB','L','MCV','MANDATORY','MCV directs anaemia classification microcytic/normocytic/macrocytic','Hematology','MCV <80 iron/thalassaemia MCV >100 B12/folate MCV 80-100 chronic disease/haemolysis'),
    ('MCV','L','FERRITIN','MANDATORY','Ferritin essential to differentiate iron deficiency from thalassaemia trait','Marker','Low ferritin confirms iron deficiency normal ferritin with low MCV thalassaemia'),
    ('MCV','H','VIT_B12','MANDATORY','B12 deficiency is a major cause of macrocytosis','Marker','Hypersegmented neutrophils on PBS confirm megaloblastic anaemia'),
    ('MCV','H','FOLATE','MANDATORY','Folate deficiency causes macrocytic megaloblastic anaemia','Marker','Always check both B12 and folate together'),
    ('MCV','H','TSH','RECOMMENDED','Hypothyroidism causes macrocytosis','Hormone','TSH elevation may explain macrocytosis without haematological cause'),
    ('MCV','H','PBS','RECOMMENDED','PBS identifies hypersegmented neutrophils in megaloblastic anaemia','Hematology','Look for hypersegmented neutrophils pathognomonic of B12/folate deficiency'),
    ('WBC','HH','PBS','MANDATORY','PBS mandatory to exclude blast cells leukaemia','Hematology','Presence of blasts indicates acute leukaemia urgent haematology'),
    ('WBC','HH','BLOOD_CS','MANDATORY','Blood cultures to exclude sepsis as cause of extreme leukocytosis','Microbiology','Sepsis can cause leukaemoid reaction with WBC >30'),
    ('WBC','HH','CRP','MANDATORY','CRP to quantify inflammatory burden','Biochemistry','High CRP with high WBC confirms severe infection/inflammation'),
    ('WBC','H','NEUT_P','MANDATORY','Differential to identify neutrophilia infection vs lymphocytosis viral','Hematology','Neutrophilia bacterial lymphocytosis viral eosinophilia parasites/allergy'),
    ('WBC','H','CRP','RECOMMENDED','CRP confirms inflammatory aetiology','Biochemistry','Elevated CRP with leucocytosis strongly suggests bacterial infection'),
    ('PLT','LL','PT','MANDATORY','DIC must be excluded in critical thrombocytopenia','Coagulation','DIC presents with thrombocytopenia + prolonged PT/aPTT + low fibrinogen + high D-dimer'),
    ('PLT','LL','FIBRIN','MANDATORY','Fibrinogen consumed in DIC low fibrinogen confirms DIC','Coagulation','Fibrinogen <1.0 g/L in DIC consider cryoprecipitate'),
    ('PLT','LL','DDIMER','MANDATORY','Elevated D-dimer in DIC','Coagulation','D-dimer very high in DIC'),
    ('PLT','LL','PBS','MANDATORY','PBS to confirm true thrombocytopenia and identify schistocytes TTP/HUS','Hematology','Schistocytes on PBS TTP/HUS urgent plasma exchange'),
    ('PLT','LL','MAL_RDT','RECOMMENDED','Malaria causes thrombocytopenia in Rwanda must be excluded','Hematology','Malaria-associated thrombocytopenia very common in sub-Saharan Africa'),
    ('PLT','L','PBS','RECOMMENDED','Blood film to confirm and assess platelet morphology','Hematology','Giant platelets suggest immune destruction'),
    ('DDIMER','H','PT','MANDATORY','DIC screen requires full coagulation panel','Coagulation','PT aPTT fibrinogen D-dimer together constitute the DIC screen'),
    ('DDIMER','H','FIBRIN','MANDATORY','Fibrinogen is consumed in DIC','Coagulation','Low fibrinogen + high D-dimer = DIC until proven otherwise'),
    ('DDIMER','H','PLT','MANDATORY','Platelet count falls in DIC','Hematology','Thrombocytopenia + coagulopathy + D-dimer = DIC'),
    ('FBG','HH','HBA1C','MANDATORY','HbA1c mandatory to assess chronic glycaemic control and confirm diabetes','Biochemistry','HbA1c >=6.5% = diabetes mellitus diagnosis'),
    ('FBG','HH','K','MANDATORY','Potassium critical in DKA hypokalaemia worsens with insulin treatment','Biochemistry','Monitor K+ closely during DKA treatment can fall rapidly'),
    ('FBG','HH','HCO3','MANDATORY','Bicarbonate to assess metabolic acidosis DKA','Biochemistry','pH <7.3 + HCO3 <15 + glucose >14 + ketones = DKA'),
    ('FBG','H','HBA1C','MANDATORY','HbA1c to confirm diabetes and assess prior glycaemic control','Biochemistry','Fasting glucose 6.1-6.9 = impaired fasting glucose HbA1c >=6.5% = diabetes'),
    ('FBG','LL','INSULIN','MANDATORY','Simultaneous fasting insulin to diagnose insulinoma','Hormone','High insulin + low glucose = insulinoma or sulphonylurea toxicity'),
    ('FBG','LL','CORT_AM','RECOMMENDED','Cortisol to exclude Addisons disease causing hypoglycaemia','Hormone','Adrenal insufficiency presents with hypoglycaemia hyponatraemia hyperkalaemia'),
    ('CREAT','HH','K','MANDATORY','Hyperkalaemia is life-threatening in acute kidney injury','Biochemistry','K+ >6.5 mmol/L in AKI requires emergency treatment'),
    ('CREAT','HH','HCO3','MANDATORY','Bicarbonate to assess metabolic acidosis in renal failure','Biochemistry','HCO3 <15 mmol/L with elevated creatinine = severe AKI'),
    ('CREAT','HH','UA_MICR','MANDATORY','Urine microscopy to identify casts type of AKI','Urinalysis','Granular casts ATN RBC casts GN WBC casts pyelonephritis/interstitial nephritis'),
    ('CREAT','H','UREA','MANDATORY','Urea:creatinine ratio distinguishes pre-renal from renal AKI','Biochemistry','Ratio >100 pre-renal dehydration <60 intrinsic renal'),
    ('CREAT','H','UA_DIP','MANDATORY','Urine dipstick for proteinuria and blood in renal impairment','Urinalysis','Proteinuria glomerular disease haematuria glomerulonephritis or urological cause'),
    ('CREAT','H','K','MANDATORY','Potassium essential in all renal impairment','Biochemistry','Even mild CKD can cause dangerous hyperkalaemia'),
    ('K','HH','CREAT','MANDATORY','Renal failure is the commonest cause of hyperkalaemia','Biochemistry','Creatinine to quantify degree of renal impairment'),
    ('K','LL','MG','MANDATORY','Hypomagnesaemia causes refractory hypokalaemia must be corrected first','Biochemistry','K+ repletion fails if Mg2+ is not corrected simultaneously'),
    ('NA','LL','CORT_AM','MANDATORY','Adrenal insufficiency Addisons causes hyponatraemia life-threatening if missed','Hormone','Morning cortisol or short Synacthen test to exclude Addisons disease'),
    ('NA','LL','TSH','MANDATORY','Hypothyroidism causes hyponatraemia SIADH-like mechanism','Hormone','TSH mandatory in hyponatraemia workup'),
    ('ALT','HH','HBSAG','MANDATORY','Hepatitis B is a major cause of acute hepatocellular damage in Africa','Serology','HBsAg to exclude acute or chronic hepatitis B with flare'),
    ('ALT','HH','ANTI_HCV','MANDATORY','Hepatitis C can cause acute hepatitis with very high transaminases','Serology','Anti-HCV screening mandatory in acute hepatitis'),
    ('ALT','HH','HAV_IGM','MANDATORY','Hepatitis A causes acute hepatitis often with very high ALT','Serology','HAV IgM confirms acute Hepatitis A usually self-limiting'),
    ('ALT','H','HBSAG','RECOMMENDED','Hepatitis B is a common cause of elevated transaminases','Serology','HBsAg if hepatitis B not previously excluded'),
    ('ALT','H','TBIL','MANDATORY','Bilirubin to assess degree of hepatic dysfunction','Biochemistry','Rising bilirubin with elevated ALT suggests hepatocellular or cholestatic disease'),
    ('ALT','H','GGT','RECOMMENDED','GGT elevation with ALT suggests alcoholic liver disease or cholestasis','Biochemistry','ALT:AST ratio >2 + elevated GGT = alcohol-related liver disease pattern'),
    ('ALP','H','GGT','MANDATORY','GGT elevation with ALP confirms hepatic not bone source','Biochemistry','Elevated GGT confirms ALP is hepatic in origin normal GGT bone source'),
    ('TBIL','H','DBIL','MANDATORY','Direct bilirubin distinguishes conjugated from unconjugated jaundice','Biochemistry','Predominantly direct hepatic or biliary obstruction predominantly indirect haemolysis or Gilberts'),
    ('TROP_I','H','CKMB','MANDATORY','CK-MB confirms myocardial source of troponin elevation','Biochemistry','CK-MB rises within 3-6h and falls faster than troponin useful for reinfarction detection'),
    ('TROP_I','H','LDH','RECOMMENDED','LDH elevation confirms significant myocardial necrosis','Biochemistry','LDH peaks at 24-48h useful when troponin delayed'),
    ('TSH','HH','FT4','MANDATORY','FT4 to confirm hypothyroidism and assess severity','Hormone','Low FT4 with elevated TSH = overt hypothyroidism requiring levothyroxine'),
    ('TSH','HH','ANTI_TPO','RECOMMENDED','Anti-TPO antibodies identify Hashimotos thyroiditis as cause','Hormone','Positive Anti-TPO confirms autoimmune thyroid disease'),
    ('TSH','LL','FT4','MANDATORY','FT4 to confirm hyperthyroidism and assess severity','Hormone','Elevated FT4 with suppressed TSH = overt hyperthyroidism'),
    ('TSH','LL','FT3','RECOMMENDED','FT3 to detect T3 toxicosis','Hormone','T3 toxicosis occurs in toxic adenoma and early Graves FT4 may be normal'),
    ('CRP','HH','BLOOD_CS','MANDATORY','Blood cultures mandatory when CRP indicates severe infection','Microbiology','Take cultures before antibiotics do not delay treatment for culture results'),
    ('CRP','HH','PCT','MANDATORY','Procalcitonin to confirm bacterial vs non-bacterial aetiology','Biochemistry','PCT >2 ug/L = bacterial sepsis PCT <0.1 = bacterial infection unlikely'),
    ('CRP','H','WBC','MANDATORY','WBC differential to identify neutrophilia bacterial or lymphocytosis viral','Hematology','High CRP + neutrophilia = bacterial infection'),
    ('AFP','H','HBSAG','MANDATORY','Hepatitis B is the major risk factor for HCC in Africa','Serology','HCC develops on background of hepatitis B/C cirrhosis in >80% of cases'),
    ('AFP','H','ANTI_HCV','MANDATORY','Hepatitis C cirrhosis is the second major HCC risk factor','Serology','Anti-HCV confirms viral hepatitis contribution to HCC risk'),
    ('PSA_T','H','PSA_F','MANDATORY','Free PSA ratio essential for risk stratification in grey zone 4-10 ng/mL','Marker','fPSA/tPSA <10% = high cancer probability >25% = lower probability'),
    ('VIT_D','LL','CA','MANDATORY','Severe vitamin D deficiency causes hypocalcaemia','Biochemistry','Check calcium before starting high-dose vitamin D supplements'),
    ('VIT_D','LL','PTH','MANDATORY','Secondary hyperparathyroidism develops in vitamin D deficiency','Hormone','PTH elevated as compensatory mechanism for low calcium'),
    ('VIT_D','LL','PHOS','RECOMMENDED','Phosphate low in osteomalacia with severe vitamin D deficiency','Biochemistry','Low calcium + low phosphate + elevated ALP + elevated PTH = osteomalacia'),
    ('MAL_RDT','POS','MAL_SM','MANDATORY','Blood smear mandatory to identify species and quantify parasitaemia','Hematology','Species identification falciparum vs vivax guides treatment choice parasitaemia >5% = severe malaria'),
    ('MAL_RDT','POS','HGB','MANDATORY','Haemolysis is the cardinal feature of malaria haemoglobin must be measured','Hematology','Hb <7 g/dL with malaria = severe malaria consider transfusion'),
    ('MAL_RDT','POS','FBG','MANDATORY','Hypoglycaemia is a life-threatening complication of falciparum malaria','Biochemistry','Check glucose especially in severe malaria pregnancy and children'),
    ('MAL_RDT','POS','PLT','MANDATORY','Thrombocytopenia is a hallmark of malaria and indicates disease severity','Hematology','PLT <50 with malaria may indicate complicated malaria'),
    ('GX_TB','H','HIV','MANDATORY','TB-HIV co-infection is common in Rwanda HIV must be tested in all TB patients','Serology','WHO mandates HIV testing in all TB patients co-infection alters treatment ART timing'),
    ('GX_TB','H','ALT','MANDATORY','Baseline LFT essential before starting hepatotoxic anti-TB drugs','Biochemistry','Anti-TB drugs rifampicin isoniazid pyrazinamide are hepatotoxic baseline ALT required'),
    ('GX_TB','H','HGB','MANDATORY','Anaemia is common in TB and influences treatment tolerance','Hematology','Severe anaemia with TB indicates haematogenous dissemination or nutritional deficiency'),
    ('HBSAG','POS','ALT','MANDATORY','LFT to assess hepatocellular damage in hepatitis B','Biochemistry','ALT elevation indicates active hepatic inflammation'),
    ('HBSAG','POS','AFP','RECOMMENDED','AFP to screen for HCC in hepatitis B','Marker','HCC risk is elevated in chronic HBsAg carriers AFP + USS surveillance recommended'),
    ('HIV','POS','GX_TB','MANDATORY','TB is the commonest opportunistic infection in HIV in Rwanda','Microbiology','All newly diagnosed HIV patients must be screened for active TB'),
    ('VDRL','POS','TPHA','MANDATORY','TPHA/TPPA confirmatory test mandatory for all reactive VDRL','Serology','VDRL can give biological false positives TPHA confirms true syphilis infection'),
    ('VDRL','POS','HIV','MANDATORY','HIV and syphilis co-infection is common HIV testing mandatory','Serology','Both are STIs with shared transmission routes always co-test'),
    ('DDIMER','H','PLT','MANDATORY','Platelets to complete DIC screen','Hematology','Thrombocytopenia + coagulopathy + elevated D-dimer = DIC'),
    ('PROLAC','HH','TSH','MANDATORY','Hypothyroidism is a common correctable cause of hyperprolactinaemia','Hormone','Treat hypothyroidism first prolactin normalises with T4 replacement'),
    ('AST','HH','CK','MANDATORY','CK to differentiate myocardial AMI from muscular rhabdomyolysis cause','Biochemistry','Very high CK with elevated AST = rhabdomyolysis or myocardial infarction'),
    ('AST','HH','TROP_I','MANDATORY','Troponin I to confirm or exclude AMI','Biochemistry','AST rises in AMI but is non-specific troponin I is cardiac-specific'),
    ('AMYL','H','LIPASE','MANDATORY','Lipase is more specific than amylase for acute pancreatitis','Biochemistry','Lipase remains elevated longer than amylase and is more specific for pancreatic disease'),
    ('AMYL','H','CA','RECOMMENDED','Hypercalcaemia is a cause of acute pancreatitis','Biochemistry','Calcium >2.8 mmol/L can precipitate acute pancreatitis'),
    ('AMYL','H','TG','RECOMMENDED','Severe hypertriglyceridaemia causes acute pancreatitis','Biochemistry','TG >11 mmol/L significantly increases pancreatitis risk'),
    ('DENGUE_NS1','POS','PLT','MANDATORY','Thrombocytopenia is the cardinal complication of dengue','Hematology','PLT monitoring essential PLT <20 indicates dengue haemorrhagic fever risk'),
    ('DENGUE_NS1','POS','HCT','MANDATORY','Haemoconcentration rising HCT indicates plasma leakage in dengue haemorrhagic fever','Hematology','HCT rise >20% from baseline = plasma leakage = dengue haemorrhagic fever'),
    ('MICRO_ALB','H','FBG','MANDATORY','Diabetes is the leading cause of microalbuminuria glucose mandatory','Biochemistry','HbA1c and glucose to assess diabetic control as cause of nephropathy'),
    ('MICRO_ALB','H','CREAT','MANDATORY','Renal function essential when proteinuria detected','Biochemistry','eGFR calculation required to stage CKD in diabetic nephropathy'),
]
