# Generated by Django 6.0.3 on 2026-05-15 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospitals/')),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('hospital_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('mission', 'Mission'), ('clinic', 'Clinic')], default='public', max_length=20)),
                ('has_lab', models.BooleanField(default=True)),
                ('has_clinic', models.BooleanField(default=True)),
                ('has_radiology', models.BooleanField(default=False)),
                ('has_pharmacy', models.BooleanField(default=False)),
                ('rbc_code', models.CharField(blank=True, help_text='Rwanda Biomedical Centre facility code', max_length=20)),
                ('minisante_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hospitals',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('color_hex', models.CharField(default='#0099FF', max_length=7)),
                ('tube_color', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core_config.hospital')),
            ],
            options={
                'db_table': 'lab_departments',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='TestCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('specimen_type', models.CharField(max_length=100)),
                ('tube_type', models.CharField(choices=[('purple_edta', 'Purple / EDTA'), ('red_plain', 'Red / Plain'), ('yellow_sst', 'Yellow / SST'), ('blue_citrate', 'Blue / Citrate'), ('green_heparin', 'Green / Heparin'), ('grey_fluoride', 'Grey / Fluoride'), ('urine_container', 'Urine Container'), ('stool_container', 'Stool Container'), ('swab', 'Swab'), ('other', 'Other')], default='red_plain', max_length=30)),
                ('tat_hours', models.DecimalField(decimal_places=1, default=2.0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference_range', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('method', models.CharField(blank=True, max_length=200)),
                ('requires_phlebotomy', models.BooleanField(default=True)),
                ('is_panel', models.BooleanField(default=False)),
                ('loinc_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order_in_department', models.PositiveSmallIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core_config.laboratorydepartment')),
                ('panel_tests', models.ManyToManyField(blank=True, to='core_config.testcatalog')),
            ],
            options={
                'db_table': 'test_catalog',
                'ordering': ['department__order', 'order_in_department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('critical_low', models.FloatField(blank=True, help_text='Value below this = Critical Low (LL)', null=True)),
                ('critical_high', models.FloatField(blank=True, help_text='Value above this = Critical High (HH)', null=True)),
                ('unit', models.CharField(max_length=50)),
                ('expected_value', models.CharField(blank=True, help_text='For qualitative tests e.g. Negative', max_length=100)),
                ('negative_value', models.CharField(blank=True, max_length=50)),
                ('positive_label', models.CharField(blank=True, max_length=50)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('', 'Any (Both)')], default='', max_length=1)),
                ('age_min_years', models.PositiveSmallIntegerField(blank=True, help_text='Minimum age (years)', null=True)),
                ('age_max_years', models.PositiveSmallIntegerField(blank=True, help_text='Maximum age (years); null = no upper limit', null=True)),
                ('method', models.CharField(blank=True, help_text='e.g. Hexokinase, Colorimetric, PCR', max_length=100)),
                ('analyzer', models.CharField(blank=True, help_text='e.g. Sysmex XN-1000, Cobas 6000', max_length=100)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active range per test/dept/sex/age group')),
                ('source', models.CharField(blank=True, help_text='e.g. WHO 2023, ISO 15189, Internal validation', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='core_config.laboratorydepartment')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='core_config.referencerange')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='core_config.testcatalog')),
            ],
            options={
                'db_table': 'reference_ranges',
                'ordering': ['test', 'department', 'sex', 'age_min_years', '-version'],
                'indexes': [models.Index(fields=['test', 'department', 'is_active'], name='reference_r_test_id_301d6f_idx'), models.Index(fields=['test', 'sex', 'age_min_years', 'is_active'], name='reference_r_test_id_e01ac5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Must match InventoryItem.name exactly', max_length=200)),
                ('item_code', models.CharField(blank=True, help_text='InventoryItem.code for exact match', max_length=30)),
                ('quantity_required', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Mandatory consumables cannot be removed from billing')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='core_config.testcatalog')),
            ],
            options={
                'db_table': 'test_consumables',
                'ordering': ['test', 'item_name'],
                'unique_together': {('test', 'item_code')},
            },
        ),
    ]
