# Generated by Django 6.0.3 on 2026-05-15 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_config', '__first__'),
        ('iot_analyzers', '__first__'),
        ('laboratory', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EQAProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('provider', models.CharField(max_length=100)),
                ('analytes', models.TextField(help_text='Comma-separated analyte names')),
                ('cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Biannual'), ('annual', 'Annual')], max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ISOClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('compliant', '✅ Compliant'), ('partial', '⚠️ Partial'), ('non_compliant', '❌ Non-Compliant'), ('na', '— N/A')], default='non_compliant', max_length=15)),
                ('evidence', models.TextField(blank=True)),
                ('evidence_files', models.JSONField(blank=True, default=list)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['clause_code'],
            },
        ),
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncr_number', models.CharField(max_length=20, unique=True)),
                ('ncr_type', models.CharField(choices=[('pre_analytical', 'Pre-analytical'), ('analytical', 'Analytical'), ('post_analytical', 'Post-analytical'), ('equipment', 'Equipment'), ('administrative', 'Administrative'), ('patient_safety', 'Patient Safety'), ('documentation', 'Documentation')], max_length=25)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('critical', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('immediate_action', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('overdue', 'Overdue')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.labrequest')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncrs_owned', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncrs_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Non-conformities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa_number', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('root_cause_analysis', models.TextField(blank=True)),
                ('steps', models.JSONField(blank=True, default=list, help_text='[{step, description, owner, due_date, completed}]')),
                ('effectiveness_check', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('verification', 'Under Verification'), ('closed', 'Closed — Effective'), ('ineffective', 'Closed — Ineffective')], default='draft', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ncr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='quality.nonconformity')),
            ],
            options={
                'verbose_name': 'CAPA',
                'verbose_name_plural': 'CAPAs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('effective_date', models.DateField()),
                ('review_date', models.DateField()),
                ('status', models.CharField(choices=[('current', '✅ Current'), ('review', '⚠️ Review Due'), ('overdue', '❌ Overdue'), ('retired', '🗃️ Retired'), ('draft', '📝 Draft')], default='draft', max_length=10)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='sops/')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sops_approved', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_config.laboratorydepartment')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EQASubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_label', models.CharField(help_text='e.g. Q2 2026', max_length=30)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('z_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('result', models.CharField(choices=[('pass', '✅ Pass'), ('fail', '❌ Fail'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('analyte_results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quality.eqaprogram')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deadline'],
                'unique_together': {('program', 'cycle_label')},
            },
        ),
        migrations.CreateModel(
            name='IQCResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyte', models.CharField(max_length=60)),
                ('control_level', models.CharField(choices=[('low', 'Low Control'), ('normal', 'Normal Control'), ('high', 'High Control')], max_length=10)),
                ('run_number', models.PositiveIntegerField()),
                ('run_date', models.DateField(default=django.utils.timezone.now)),
                ('measured_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('target_mean', models.DecimalField(decimal_places=3, max_digits=10)),
                ('target_sd', models.DecimalField(decimal_places=4, max_digits=8)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('z_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('cv_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bias_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('westgard_status', models.CharField(choices=[('pass', '✅ Pass'), ('warning', '⚠️ 1:2S Warning'), ('reject', '❌ Reject')], default='pass', max_length=10)),
                ('westgard_rule', models.CharField(blank=True, help_text='e.g. 1:3S, 2:2S, 10x', max_length=20)),
                ('shift', models.CharField(blank=True, max_length=20)),
                ('action_taken', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot_analyzers.analyzerdevice')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iqc_runs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iqc_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['analyte', 'run_number'],
                'indexes': [models.Index(fields=['analyte', 'control_level', 'run_date'], name='quality_iqc_analyte_1f9c49_idx')],
            },
        ),
        migrations.CreateModel(
            name='SOPSignoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoffs', to='quality.sopdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_at'],
                'unique_together': {('sop', 'user')},
            },
        ),
    ]
