# Generated by Django 6.0.3 on 2026-05-15 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '__first__'),
        ('patients', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToxicologyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('uds', 'Urine Drug Screen'), ('tdm', 'Therapeutic Drug Monitoring'), ('poisoning', 'Poisoning Assessment'), ('forensic', 'Forensic Toxicology')], max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resulted', 'Resulted'), ('validated', 'Validated')], default='pending', max_length=15)),
                ('is_medicolegal', models.BooleanField(default=False)),
                ('chain_of_custody_id', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toxicology', to='laboratory.labrequest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toxicology_requests', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TDMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=60)),
                ('measured_level', models.DecimalField(decimal_places=3, max_digits=8)),
                ('unit', models.CharField(max_length=20)),
                ('sample_timing', models.CharField(choices=[('trough', 'Trough (pre-dose)'), ('peak', 'Peak (post-dose)'), ('random', 'Random')], max_length=10)),
                ('patient_weight', models.DecimalField(blank=True, decimal_places=1, help_text='kg', max_digits=5, null=True)),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('indication', models.CharField(blank=True, max_length=200)),
                ('dose_regimen', models.CharField(blank=True, max_length=100)),
                ('therapeutic_range_lo', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('therapeutic_range_hi', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('interp_status', models.CharField(blank=True, choices=[('sub', 'Sub-therapeutic'), ('thera', 'Therapeutic'), ('supra', 'Supra-therapeutic (Toxic)')], max_length=10)),
                ('ai_interpretation', models.JSONField(blank=True, default=dict)),
                ('dose_recommendation', models.TextField(blank=True)),
                ('toxicity_risk', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated')], default='draft', max_length=15)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tdm', to='toxicology.toxicologyrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoisoningCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(choices=[('organophosphate', 'Organophosphates / Pesticides'), ('paracetamol', 'Paracetamol / Acetaminophen'), ('salicylate', 'Salicylates (Aspirin)'), ('alcohol', 'Ethanol (Alcohol)'), ('methanol', 'Methanol / Ethylene Glycol'), ('heavy_metal', 'Heavy Metals (Pb, As, Hg)'), ('co', 'Carbon Monoxide'), ('cyanide', 'Cyanide'), ('benzodiazepine', 'Benzodiazepines'), ('opioid', 'Opioids / Morphine'), ('rodenticide', 'Rodenticide (Warfarin-type)'), ('other', 'Other')], max_length=30)),
                ('substance_other', models.CharField(blank=True, max_length=100)),
                ('concentration', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('concentration_unit', models.CharField(blank=True, max_length=20)),
                ('sample_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('gastric', 'Gastric Content'), ('hair', 'Hair')], default='blood', max_length=30)),
                ('time_since_exposure', models.DecimalField(blank=True, decimal_places=1, help_text='Hours', max_digits=5, null=True)),
                ('is_medicolegal', models.BooleanField(default=False)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('lethal', 'Potentially Lethal')], max_length=15)),
                ('lethal_threshold_exceeded', models.BooleanField(default=False)),
                ('ai_assessment', models.JSONField(blank=True, default=dict)),
                ('management_guidance', models.TextField(blank=True)),
                ('antidote', models.CharField(blank=True, max_length=200)),
                ('antidote_dose', models.CharField(blank=True, max_length=200)),
                ('referral_needed', models.BooleanField(default=False)),
                ('referral_facility', models.CharField(blank=True, max_length=100)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poisoning', to='toxicology.toxicologyrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrugScreenResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_type', models.CharField(choices=[('5', '5-Panel Standard'), ('10', '10-Panel Extended'), ('12', '12-Panel Comprehensive')], default='5', max_length=5)),
                ('drug_results', models.JSONField(blank=True, default=dict)),
                ('screening_method', models.CharField(choices=[('immunoassay', 'Immunoassay (IA)'), ('gcms', 'GC-MS'), ('lcms', 'LC-MS/MS'), ('rdt', 'Rapid Dipstrip')], default='Immunoassay', max_length=50)),
                ('coc_required', models.BooleanField(default=False)),
                ('specimen_temp_ok', models.BooleanField(default=True, help_text='Specimen temperature within acceptable range')),
                ('creatinine_ok', models.BooleanField(default=True, help_text='Specimen creatinine acceptable')),
                ('specific_gravity_ok', models.BooleanField(default=True)),
                ('ai_interpretation', models.JSONField(blank=True, default=dict)),
                ('positive_drugs', models.JSONField(blank=True, default=list)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('confirmed', 'GC-MS Confirmed')], default='draft', max_length=15)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drug_screen', to='toxicology.toxicologyrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
