# Generated by Django 6.0.3 on 2026-05-15 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '__first__'),
        ('patients', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HematologyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('resulted', 'Resulted'), ('validated', 'Validated'), ('authorized', 'Authorized'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('sample_received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hematology', to='laboratory.labrequest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hematology_requests', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoagulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt', models.DecimalField(blank=True, decimal_places=1, help_text='sec', max_digits=6, null=True)),
                ('inr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aptt', models.DecimalField(blank=True, decimal_places=1, help_text='sec', max_digits=6, null=True)),
                ('fibrinogen', models.DecimalField(blank=True, decimal_places=2, help_text='g/L', max_digits=5, null=True)),
                ('d_dimer', models.DecimalField(blank=True, decimal_places=3, help_text='µg/mL', max_digits=6, null=True)),
                ('tt', models.DecimalField(blank=True, decimal_places=1, help_text='sec', max_digits=6, null=True)),
                ('anticoagulant_therapy', models.CharField(blank=True, max_length=50)),
                ('ai_interpretation', models.JSONField(blank=True, default=dict)),
                ('primary_finding', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(default='normal', max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated')], default='draft', max_length=15)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coagulation', to='hematology.hematologyrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CBCResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzer', models.CharField(blank=True, max_length=100)),
                ('wbc', models.DecimalField(blank=True, decimal_places=2, help_text='×10³/µL', max_digits=6, null=True)),
                ('rbc', models.DecimalField(blank=True, decimal_places=2, help_text='×10⁶/µL', max_digits=5, null=True)),
                ('hgb', models.DecimalField(blank=True, decimal_places=1, help_text='g/dL', max_digits=5, null=True)),
                ('hct', models.DecimalField(blank=True, decimal_places=1, help_text='%', max_digits=5, null=True)),
                ('mcv', models.DecimalField(blank=True, decimal_places=1, help_text='fL', max_digits=5, null=True)),
                ('mch', models.DecimalField(blank=True, decimal_places=1, help_text='pg', max_digits=5, null=True)),
                ('mchc', models.DecimalField(blank=True, decimal_places=1, help_text='g/dL', max_digits=5, null=True)),
                ('rdw', models.DecimalField(blank=True, decimal_places=1, help_text='%', max_digits=5, null=True)),
                ('neut_pct', models.DecimalField(blank=True, decimal_places=1, help_text='%', max_digits=5, null=True)),
                ('lymph_pct', models.DecimalField(blank=True, decimal_places=1, help_text='%', max_digits=5, null=True)),
                ('mono_pct', models.DecimalField(blank=True, decimal_places=1, help_text='%', max_digits=5, null=True)),
                ('eo_pct', models.DecimalField(blank=True, decimal_places=1, help_text='%', max_digits=5, null=True)),
                ('baso_pct', models.DecimalField(blank=True, decimal_places=1, help_text='%', max_digits=5, null=True)),
                ('blast_pct', models.DecimalField(blank=True, decimal_places=1, help_text='% — flag if >0', max_digits=4, null=True)),
                ('neut_abs', models.DecimalField(blank=True, decimal_places=2, help_text='×10³/µL ANC', max_digits=5, null=True)),
                ('lymph_abs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mono_abs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('plt', models.DecimalField(blank=True, decimal_places=0, help_text='×10³/µL', max_digits=6, null=True)),
                ('mpv', models.DecimalField(blank=True, decimal_places=1, help_text='fL', max_digits=5, null=True)),
                ('primary_finding', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], default='normal', max_length=15)),
                ('ai_interpretation', models.JSONField(blank=True, default=dict)),
                ('critical_values', models.JSONField(blank=True, default=list)),
                ('leukemia_flag', models.BooleanField(default=False)),
                ('reflex_suggestions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('resulted', 'Resulted'), ('validated', 'Validated'), ('authorized', 'Authorized')], default='draft', max_length=15)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('correction_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbc_authorized', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbc_validated', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cbc', to='hematology.hematologyrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InflammationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esr', models.DecimalField(blank=True, decimal_places=0, help_text='mm/hr', max_digits=5, null=True)),
                ('crp', models.DecimalField(blank=True, decimal_places=2, help_text='mg/L', max_digits=7, null=True)),
                ('pct', models.DecimalField(blank=True, decimal_places=3, help_text='µg/L', max_digits=6, null=True)),
                ('ferritin', models.DecimalField(blank=True, decimal_places=1, help_text='µg/L', max_digits=8, null=True)),
                ('ldh', models.DecimalField(blank=True, decimal_places=0, help_text='U/L', max_digits=7, null=True)),
                ('il6', models.DecimalField(blank=True, decimal_places=2, help_text='pg/mL', max_digits=7, null=True)),
                ('patient_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ai_interpretation', models.JSONField(blank=True, default=dict)),
                ('primary_finding', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(default='normal', max_length=15)),
                ('sepsis_alert', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated')], default='draft', max_length=15)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inflammation', to='hematology.hematologyrequest')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmearResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stain_type', models.CharField(choices=[('leishman', 'Leishman'), ('giemsa', 'Giemsa'), ('wright', 'Wright'), ('mgg', 'May-Grünwald Giemsa'), ('hne', 'H&E')], default='leishman', max_length=50)),
                ('film_type', models.CharField(choices=[('thin', 'Thin Film (differential)'), ('thick', 'Thick Film (parasite)')], default='thin', max_length=20)),
                ('magnification', models.CharField(default='100x', max_length=20)),
                ('smear_image', models.ImageField(blank=True, null=True, upload_to='smear_images/')),
                ('red_cell_morphology', models.JSONField(blank=True, default=list, help_text='[{name, pct, color}] — morphology distribution')),
                ('wbc_differential', models.JSONField(blank=True, default=dict, help_text='{neutrophils, lymphocytes, monocytes, eosinophils, basophils, blast}')),
                ('platelet_estimate', models.CharField(blank=True, max_length=30)),
                ('parasite_detected', models.CharField(blank=True, max_length=100)),
                ('parasite_stage', models.CharField(blank=True, max_length=100)),
                ('impression', models.TextField(blank=True)),
                ('ai_confidence', models.PositiveSmallIntegerField(default=0, help_text='0–100%')),
                ('ai_raw', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ai_pending', 'AI Processing'), ('resulted', 'Resulted'), ('validated', 'Validated')], default='draft', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smear', to='hematology.hematologyrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smears_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
