# Generated by Django 6.0.3 on 2026-05-15 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '__first__'),
        ('patients', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroscopySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_code', models.CharField(max_length=15)),
                ('stain_type', models.CharField(choices=[('he', 'H&E'), ('pas', 'PAS'), ('masson', 'Masson Trichrome'), ('giemsa', 'Giemsa'), ('ziehl', 'Ziehl-Neelsen (AFB)'), ('gms', 'GMS (fungal)'), ('prussian', 'Prussian Blue (iron)'), ('gram', 'Gram stain'), ('congo', 'Congo Red (amyloid)'), ('other', 'Other')], default='he', max_length=15)),
                ('cut_at', models.DateTimeField(blank=True, null=True)),
                ('slide_image', models.ImageField(blank=True, null=True, upload_to='pathology/slides/')),
                ('wsi_url', models.URLField(blank=True, help_text='Whole-slide image URL (digital pathology)')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['slide_code'],
            },
        ),
        migrations.CreateModel(
            name='PathologyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=30, unique=True)),
                ('case_type', models.CharField(choices=[('biopsy', 'Biopsy (Histology)'), ('cytology', 'Cytology (Pap / Non-Gyn)'), ('fna', 'Fine-Needle Aspiration (FNA)'), ('resection', 'Surgical Resection'), ('frozen', 'Frozen Section'), ('autopsy', 'Autopsy / Post-mortem'), ('bone_marrow', 'Bone Marrow Trephine'), ('flowcyto', 'Flow Cytometry')], max_length=15)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent (48h)'), ('stat', 'STAT — Intraoperative')], default='routine', max_length=10)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('grossing', 'Grossing'), ('processing', 'Tissue Processing'), ('embedding', 'Embedding'), ('sectioning', 'Sectioning'), ('staining', 'Staining'), ('microscopy', 'Microscopy'), ('ai_review', 'AI Vision Review'), ('reporting', 'Reporting'), ('validated', 'Validated'), ('authorized', 'Authorized / Signed Out'), ('amended', 'Amended')], default='registered', max_length=15)),
                ('specimen_site', models.CharField(max_length=200)),
                ('specimen_laterality', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('bilateral', 'Bilateral'), ('midline', 'Midline')], max_length=10)),
                ('specimen_count', models.PositiveSmallIntegerField(default=1)),
                ('fixative', models.CharField(choices=[('formalin', 'Formalin 10%'), ('bouin', "Bouin's"), ('alcohol', 'Alcohol'), ('fresh', 'Fresh (frozen)'), ('glutaraldehyde', 'Glutaraldehyde')], default='Formalin 10%', max_length=50)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('clinical_information', models.TextField(blank=True)),
                ('requesting_clinician', models.CharField(blank=True, max_length=100)),
                ('provisional_diagnosis', models.CharField(blank=True, max_length=200)),
                ('procedure_type', models.CharField(blank=True, help_text='e.g. TURBT, core needle biopsy', max_length=100)),
                ('ihc_requested', models.BooleanField(default=False)),
                ('special_stains_requested', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_pathologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathology_cases', to=settings.AUTH_USER_MODEL)),
                ('lab_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.labrequest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pathology_cases', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IHCPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.CharField(help_text='e.g. ER, PR, HER2, Ki-67, CD20', max_length=60)),
                ('clone', models.CharField(blank=True, max_length=50)),
                ('result', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('equivocal', 'Equivocal (2+)'), ('not_done', 'Not Done')], max_length=20)),
                ('intensity', models.CharField(blank=True, choices=[('weak', 'Weak (1+)'), ('moderate', 'Moderate (2+)'), ('strong', 'Strong (3+)')], max_length=20)),
                ('percentage', models.PositiveSmallIntegerField(blank=True, help_text='% positive cells', null=True)),
                ('h_score', models.PositiveSmallIntegerField(blank=True, help_text='H-score 0–300', null=True)),
                ('allred_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ihc_panels', to='pathology.pathologycase')),
            ],
            options={
                'ordering': ['marker'],
            },
        ),
        migrations.CreateModel(
            name='HistopathologyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_status', models.CharField(choices=[('draft', 'Draft'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('amended', 'Amended'), ('addendum', 'Addendum')], default='draft', max_length=15)),
                ('gross_description', models.TextField(blank=True)),
                ('specimen_weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('specimen_size_cm', models.CharField(blank=True, help_text='e.g. 3.5 × 2.1 × 1.8 cm', max_length=50)),
                ('microscopic_description', models.TextField(blank=True)),
                ('diagnosis', models.TextField()),
                ('icd10_code', models.CharField(blank=True, max_length=15)),
                ('icd_o_morphology', models.CharField(blank=True, help_text='ICD-O morphology code e.g. 8140/3', max_length=20)),
                ('snomed_concept', models.CharField(blank=True, max_length=50)),
                ('is_malignant', models.BooleanField(blank=True, null=True)),
                ('tumor_grade', models.CharField(choices=[('G1', 'Grade 1 — Well differentiated'), ('G2', 'Grade 2 — Moderately differentiated'), ('G3', 'Grade 3 — Poorly differentiated'), ('G4', 'Grade 4 — Undifferentiated'), ('GX', 'GX — Grade cannot be assessed'), ('NA', 'Not applicable')], default='NA', max_length=5)),
                ('pT', models.CharField(blank=True, help_text='Pathological T stage', max_length=10)),
                ('pN', models.CharField(blank=True, max_length=10)),
                ('pM', models.CharField(blank=True, max_length=10)),
                ('tnm_stage', models.CharField(blank=True, max_length=15)),
                ('lymphovascular_invasion', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('indeterminate', 'Indeterminate')], max_length=20)),
                ('perineural_invasion', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('indeterminate', 'Indeterminate')], max_length=20)),
                ('resection_margins', models.CharField(blank=True, choices=[('clear', 'Clear — Margins free'), ('close', 'Close (<1mm)'), ('involved', 'Margins involved')], max_length=30)),
                ('ai_assisted', models.BooleanField(default=False)),
                ('ai_suggestions', models.JSONField(blank=True, default=dict)),
                ('comments', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('amendment_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_countersigned', to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_signed', to=settings.AUTH_USER_MODEL)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='pathology.pathologycase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlideAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(choices=[('nexus_vision', 'NEXUS AI Vision'), ('pathai', 'PathAI'), ('paige', 'Paige.AI'), ('manual', 'Manual (No AI)')], default='nexus_vision', max_length=20)),
                ('ai_version', models.CharField(blank=True, max_length=20)),
                ('confidence', models.PositiveSmallIntegerField(default=0, help_text='0–100%')),
                ('cancer_probability', models.DecimalField(blank=True, decimal_places=2, help_text='0–100%', max_digits=5, null=True)),
                ('detected_patterns', models.JSONField(blank=True, default=list, help_text='[{pattern, confidence, region_coords}]')),
                ('cell_classification', models.JSONField(blank=True, default=dict, help_text='{malignant_pct, benign_pct, necrosis_pct, ...}')),
                ('ki67_index', models.DecimalField(blank=True, decimal_places=1, help_text='Proliferation index %', max_digits=5, null=True)),
                ('mitotic_count', models.PositiveSmallIntegerField(blank=True, help_text='Per 10 HPF', null=True)),
                ('ai_impression', models.TextField(blank=True)),
                ('ai_raw_output', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('analysed_at', models.DateTimeField(auto_now_add=True)),
                ('slide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='pathology.microscopyslide')),
            ],
            options={
                'ordering': ['-analysed_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecimenBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_code', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('cassette_color', models.CharField(blank=True, max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pathology.pathologycase')),
            ],
            options={
                'ordering': ['block_code'],
                'unique_together': {('case', 'block_code')},
            },
        ),
        migrations.AddField(
            model_name='microscopyslide',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='pathology.specimenblock'),
        ),
    ]
